//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APSBudgetDetail
    {
        public APSBudgetDetail()
        {
            this.APSPayables = new HashSet<APSPayable>();
            this.APSTransacts = new HashSet<APSTransact>();
            this.Vendors = new HashSet<Vendor>();
        }
    
        public string APSBudgetDetail_Key { get; set; }
        public string APSBudget_Key { get; set; }
        public string Fiscal_Key { get; set; }
        public decimal BudgetAmount { get; set; }
        public decimal BudgetBalance { get; set; }
        public decimal WarningLevel { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public byte[] TimeStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual APSBudget APSBudget { get; set; }
        public virtual ICollection<APSPayable> APSPayables { get; set; }
        public virtual ICollection<APSTransact> APSTransacts { get; set; }
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}
