//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARSBudgetDetail
    {
        public ARSBudgetDetail()
        {
            this.ARSInvoiceApprovals = new HashSet<ARSInvoiceApproval>();
            this.ARSInvoiceDetails = new HashSet<ARSInvoiceDetail>();
        }
    
        public string ARSBudgetDetail_Key { get; set; }
        public string ARSBudget_Key { get; set; }
        public string Fiscal_Key { get; set; }
        public decimal BudgetAmount { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public byte[] TimeStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ARSBudget ARSBudget { get; set; }
        public virtual ICollection<ARSInvoiceApproval> ARSInvoiceApprovals { get; set; }
        public virtual ICollection<ARSInvoiceDetail> ARSInvoiceDetails { get; set; }
    }
}
