//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARSBudget
    {
        public ARSBudget()
        {
            this.ARSBudgetDetails = new HashSet<ARSBudgetDetail>();
        }
    
        public string ARSBudget_Key { get; set; }
        public string Organization_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NameDesc { get; set; }
        public string LongName { get; set; }
        public byte Active { get; set; }
        public int AttachedDocuments { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public byte[] TimeStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<ARSBudgetDetail> ARSBudgetDetails { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
