//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARSContract
    {
        public ARSContract()
        {
            this.ARSInvoiceApprovals = new HashSet<ARSInvoiceApproval>();
            this.ARSInvoiceDetails = new HashSet<ARSInvoiceDetail>();
        }
    
        public string ARSContract_Key { get; set; }
        public string Customer_Key { get; set; }
        public string ContractNumber { get; set; }
        public decimal ContractAmount { get; set; }
        public Nullable<decimal> ContractBalance { get; set; }
        public Nullable<decimal> TotalPayments { get; set; }
        public Nullable<decimal> WarningLevel { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Comments { get; set; }
        public byte Active { get; set; }
        public Nullable<int> AttachedDocuments { get; set; }
        public string NameDesc { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<ARSInvoiceApproval> ARSInvoiceApprovals { get; set; }
        public virtual ICollection<ARSInvoiceDetail> ARSInvoiceDetails { get; set; }
    }
}
