//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARSCanceledPaymentDetail
    {
        public string ARSCanceledPaymentDetail_Key { get; set; }
        public string ARSCanceledPayment_Key { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<short> ItemNumber { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ARSCanceledPayment ARSCanceledPayment { get; set; }
    }
}
