//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARSPayment
    {
        public ARSPayment()
        {
            this.ARSPaymentDetails = new HashSet<ARSPaymentDetail>();
        }
    
        public string ARSPayment_Key { get; set; }
        public string Organization_Key { get; set; }
        public string Customer_Key { get; set; }
        public string CheckNumber { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public decimal Amount { get; set; }
        public decimal PaymentBalance { get; set; }
        public string Type { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public byte[] TimeStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<ARSPaymentDetail> ARSPaymentDetails { get; set; }
    }
}
