//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDLClass
    {
        public CDLClass()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public string CDLClass_Key { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
