//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public string Config_Key { get; set; }
        public string County_Key { get; set; }
        public Nullable<double> Last_ID { get; set; }
        public string Support_Information { get; set; }
        public string Phone_Support_Num { get; set; }
        public string Fax_Support_Num { get; set; }
        public string Support_EMail_Address { get; set; }
        public string Support_Address { get; set; }
        public string Employee_Rate_Default { get; set; }
        public Nullable<short> OH_Calc_Method { get; set; }
        public string SMTP_Domain_Name { get; set; }
        public short Roads_Leading_Zeros { get; set; }
        public string Default_Budget_No { get; set; }
        public string DefaultDocumentPath { get; set; }
        public string DefaultSRSEmailFromAddress { get; set; }
        public byte EnableErrorReporting { get; set; }
        public byte MMSIncludeProjectCost { get; set; }
        public byte SecurityEnabled { get; set; }
        public byte CRWSecurityEnabled { get; set; }
        public byte PostBillableTimecardsToARS { get; set; }
        public byte AutoLogin { get; set; }
        public byte ShowErrorForm { get; set; }
        public byte EnableBeepSound { get; set; }
        public byte EnableStreetWise { get; set; }
        public Nullable<short> Projection { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
        public byte SetAllSecurityToAdmin { get; set; }
        public bool EquipmentDepreciationUsesCasHours { get; set; }
    
        public virtual County County { get; set; }
    }
}
