//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class County
    {
        public County()
        {
            this.Configs = new HashSet<Config>();
            this.CountyUtilities = new HashSet<CountyUtility>();
            this.FuelImportSchemas = new HashSet<FuelImportSchema>();
        }
    
        public string County_Key { get; set; }
        public string County_Num { get; set; }
        public string County_Name { get; set; }
    
        public virtual ICollection<Config> Configs { get; set; }
        public virtual ICollection<CountyUtility> CountyUtilities { get; set; }
        public virtual ICollection<FuelImportSchema> FuelImportSchemas { get; set; }
    }
}
