//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewEmployee
    {
        public string CrewEmployee_Key { get; set; }
        public string CrewSheet_Key { get; set; }
        public string Employee_Key { get; set; }
        public string PayType_Key { get; set; }
        public decimal Hours { get; set; }
        public Nullable<decimal> OverrideLabor { get; set; }
        public string Premium_Key { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual CrewSheet CrewSheet { get; set; }
    }
}
