//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewSheet
    {
        public CrewSheet()
        {
            this.CrewEmployees = new HashSet<CrewEmployee>();
            this.CrewEquipments = new HashSet<CrewEquipment>();
            this.CrewMaterials = new HashSet<CrewMaterial>();
            this.CrewServices = new HashSet<CrewService>();
        }
    
        public string CrewSheet_Key { get; set; }
        public string CrewName { get; set; }
        public Nullable<System.DateTime> Task_Date { get; set; }
        public string Crew_Num { get; set; }
        public string Activity_Key { get; set; }
        public Nullable<decimal> Production { get; set; }
        public string Mgt_Unit_Key { get; set; }
        public string Program_Key { get; set; }
        public string Premium_Key { get; set; }
        public string Zone_Key { get; set; }
        public string Project_Key { get; set; }
        public string RBF_Key { get; set; }
        public string Road_Key { get; set; }
        public Nullable<decimal> Beg_Point { get; set; }
        public Nullable<decimal> End_Point { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public string Reason_Key { get; set; }
        public string SRSRequestNumber { get; set; }
        public string Comments { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ICollection<CrewEmployee> CrewEmployees { get; set; }
        public virtual ICollection<CrewEquipment> CrewEquipments { get; set; }
        public virtual ICollection<CrewMaterial> CrewMaterials { get; set; }
        public virtual ICollection<CrewService> CrewServices { get; set; }
        public virtual Project Project { get; set; }
        public virtual RBF RBF { get; set; }
        public virtual Reason Reason { get; set; }
        public virtual Road Road { get; set; }
        public virtual Zone Zone { get; set; }
        public virtual Program Program { get; set; }
    }
}
