//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewEquipment
    {
        public string CrewEquipment_Key { get; set; }
        public string CrewSheet_Key { get; set; }
        public string Equipment_Key { get; set; }
        public string Employee_Key { get; set; }
        public decimal Hours { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual CrewSheet CrewSheet { get; set; }
    }
}
