//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRWSaveReportUser
    {
        public string CRWSaveReportUser_Key { get; set; }
        public string CRWSaveReport_Key { get; set; }
        public byte SecurityLevel { get; set; }
        public Nullable<int> TotalRan { get; set; }
        public Nullable<System.DateTime> LastRanDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual CRWSaveReport CRWSaveReport { get; set; }
        public virtual SecurityUser SecurityUser { get; set; }
    }
}
