//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Contact
    {
        public string Customer_Contact_Key { get; set; }
        public string Customer_Key { get; set; }
        public Nullable<System.DateTime> Contact_Date { get; set; }
        public string Contact_Person { get; set; }
        public string Contacted_By { get; set; }
        public string Issue { get; set; }
        public string Resolution { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    }
}
