//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseVersion
    {
        public int DatabaseVersion_Key { get; set; }
        public string DatabaseVersion1 { get; set; }
        public string LastPatchRan { get; set; }
        public string PMPDatabaseVersion { get; set; }
        public string PMPLastPatchRan { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
    }
}
