//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropDownDetail
    {
        public string DropDownDetail_Key { get; set; }
        public string DropDown_Key { get; set; }
        public string SecurityUser_Key { get; set; }
        public byte DropDownOrder { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
    
        public virtual SecurityUser SecurityUser { get; set; }
    }
}
