//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dropdown
    {
        public string DropDown_Key { get; set; }
        public string SecurityObject_Key { get; set; }
        public string SPROCName { get; set; }
        public string SPROCDescription { get; set; }
        public byte SystemRecord { get; set; }
        public byte DefaultOrder { get; set; }
        public byte Editable { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
    }
}
