//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRate
    {
        public string EmployeeRate_Key { get; set; }
        public string Employee_Key { get; set; }
        public string PayChangeType_Key { get; set; }
        public Nullable<System.DateTime> BegDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public decimal Rate { get; set; }
        public decimal FringeRate { get; set; }
        public decimal OverheadRate { get; set; }
        public decimal OtherRate { get; set; }
        public decimal FullBurdenRate { get; set; }
        public decimal OHCost { get; set; }
        public byte OH_Calc_Method { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PayChangeType PayChangeType { get; set; }
    }
}
