//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAudit
    {
        public int EmployeeAudit_Key { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionType { get; set; }
        public string UserName { get; set; }
        public string AuditComments { get; set; }
        public string Employee_Key { get; set; }
        public string Employee_Num { get; set; }
        public string PayrollEmployeeNumber { get; set; }
        public string ResourceClass_Key { get; set; }
        public string OH_Class_Key { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Initial { get; set; }
        public string FullName { get; set; }
        public string SSN { get; set; }
        public string Position_Key { get; set; }
        public Nullable<byte> Supervisor { get; set; }
        public string SupervisorName { get; set; }
        public string Department_Key { get; set; }
        public string Mgt_Unit_Key { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<byte> PaySchedule { get; set; }
        public string PayRange { get; set; }
        public string PayRangeStep { get; set; }
        public string DriversLicense { get; set; }
        public Nullable<System.DateTime> DriversLicenseExp { get; set; }
        public string States_Key { get; set; }
        public Nullable<byte> CDL { get; set; }
        public string CDLClass_Key { get; set; }
        public Nullable<System.DateTime> IccMedCardExp { get; set; }
        public string UnionName { get; set; }
        public string Fund { get; set; }
        public string Seniority { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Extension { get; set; }
        public string PagerNumber { get; set; }
        public string CellNumber { get; set; }
        public string MaritalStatus { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Doctor { get; set; }
        public string DoctorAddress { get; set; }
        public string DoctorPhone { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Fringe_Rate { get; set; }
        public Nullable<decimal> Overhead_Rate { get; set; }
        public Nullable<decimal> Other_Rate { get; set; }
        public Nullable<decimal> Full_Burden_Rate { get; set; }
        public string Rate_Calculation { get; set; }
        public byte Active { get; set; }
        public byte ExtraHelp { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> TerminateDate { get; set; }
        public Nullable<System.DateTime> LastPromotionDate { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public Nullable<System.DateTime> NextPayStepDate { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    }
}
