//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeIssueItem
    {
        public string EmployeeIssueItem_Key { get; set; }
        public string Employee_Key { get; set; }
        public string EmployeeItem_Key { get; set; }
        public string SerialNumber { get; set; }
        public string ModelNumber { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmployeeItem EmployeeItem { get; set; }
    }
}
