//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeCertifications = new HashSet<EmployeeCertification>();
            this.EmployeeRates = new HashSet<EmployeeRate>();
            this.EMSEmployeeHistories = new HashSet<EMSEmployeeHistory>();
            this.EMSWorkOrderDetails = new HashSet<EMSWorkOrderDetail>();
            this.EMSWorkOrderSaveds = new HashSet<EMSWorkOrderSaved>();
            this.EmployeeIssueItems = new HashSet<EmployeeIssueItem>();
            this.SecurityUsers = new HashSet<SecurityUser>();
            this.TimeAccruals = new HashSet<TimeAccrual>();
            this.InventoryTransferDetails = new HashSet<InventoryTransferDetail>();
            this.PayVarianceDatas = new HashSet<PayVarianceData>();
            this.TimeCards = new HashSet<TimeCard>();
            this.Transacts = new HashSet<Transact>();
            this.Transact_History = new HashSet<Transact_History>();
            this.VMSSprayReportEmployees = new HashSet<VMSSprayReportEmployee>();
        }
    
        public string Employee_Key { get; set; }
        public string Employee_Num { get; set; }
        public string PayrollEmployeeNumber { get; set; }
        public string ResourceClass_Key { get; set; }
        public string CRWResourceClassUVW_Key { get; set; }
        public string OH_Class_Key { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Initial { get; set; }
        public string FullName { get; set; }
        public string NameDesc { get; set; }
        public string DescName { get; set; }
        public string EmployeeNumFullName { get; set; }
        public string FullNameEmployeeNum { get; set; }
        public string Position_Key { get; set; }
        public Nullable<byte> Supervisor { get; set; }
        public string SupervisorName { get; set; }
        public string Department_Key { get; set; }
        public string Mgt_Unit_Key { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<byte> PaySchedule { get; set; }
        public string PayRange { get; set; }
        public string PayRangeStep { get; set; }
        public Nullable<System.DateTime> DriversLicenseExp { get; set; }
        public string States_Key { get; set; }
        public Nullable<byte> CDL { get; set; }
        public string CDLClass_Key { get; set; }
        public Nullable<System.DateTime> IccMedCardExp { get; set; }
        public string UnionName { get; set; }
        public string Fund { get; set; }
        public string Seniority { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Extension { get; set; }
        public string PagerNumber { get; set; }
        public string CellNumber { get; set; }
        public string MaritalStatus { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Doctor { get; set; }
        public string DoctorAddress { get; set; }
        public string DoctorPhone { get; set; }
        public string Rate_Calculation { get; set; }
        public byte Active { get; set; }
        public byte ExtraHelp { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> TerminateDate { get; set; }
        public Nullable<System.DateTime> LastPromotionDate { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public Nullable<System.DateTime> NextPayStepDate { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual CDLClass CDLClass { get; set; }
        public virtual Department Department { get; set; }
        public virtual OH_Class OH_Class { get; set; }
        public virtual ResourceClass ResourceClass { get; set; }
        public virtual Mgt_Unit Mgt_Unit { get; set; }
        public virtual ICollection<EmployeeCertification> EmployeeCertifications { get; set; }
        public virtual ICollection<EmployeeRate> EmployeeRates { get; set; }
        public virtual ICollection<EMSEmployeeHistory> EMSEmployeeHistories { get; set; }
        public virtual ICollection<EMSWorkOrderDetail> EMSWorkOrderDetails { get; set; }
        public virtual ICollection<EMSWorkOrderSaved> EMSWorkOrderSaveds { get; set; }
        public virtual ICollection<EmployeeIssueItem> EmployeeIssueItems { get; set; }
        public virtual ICollection<SecurityUser> SecurityUsers { get; set; }
        public virtual ICollection<TimeAccrual> TimeAccruals { get; set; }
        public virtual ICollection<InventoryTransferDetail> InventoryTransferDetails { get; set; }
        public virtual ICollection<PayVarianceData> PayVarianceDatas { get; set; }
        public virtual Position Position { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
        public virtual ICollection<Transact> Transacts { get; set; }
        public virtual ICollection<Transact_History> Transact_History { get; set; }
        public virtual ICollection<VMSSprayReportEmployee> VMSSprayReportEmployees { get; set; }
    }
}
