//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSMeterType
    {
        public EMSMeterType()
        {
            this.Equipments = new HashSet<Equipment>();
        }
    
        public string EMSMeterType_Key { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Equipment> Equipments { get; set; }
    }
}
