//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSPMMethod
    {
        public EMSPMMethod()
        {
            this.EMSHistories = new HashSet<EMSHistory>();
            this.EMSMaintEntries = new HashSet<EMSMaintEntry>();
            this.Equipments = new HashSet<Equipment>();
            this.EMSPolicies = new HashSet<EMSPolicy>();
            this.EMSWorkOrderDetails = new HashSet<EMSWorkOrderDetail>();
        }
    
        public string EMSPMMethod_Key { get; set; }
        public string Name { get; set; }
        public string NameDesc { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<EMSHistory> EMSHistories { get; set; }
        public virtual ICollection<EMSMaintEntry> EMSMaintEntries { get; set; }
        public virtual ICollection<Equipment> Equipments { get; set; }
        public virtual ICollection<EMSPolicy> EMSPolicies { get; set; }
        public virtual ICollection<EMSWorkOrderDetail> EMSWorkOrderDetails { get; set; }
    }
}
