//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSPartList
    {
        public EMSPartList()
        {
            this.EMSHistories = new HashSet<EMSHistory>();
        }
    
        public string EMSPartList_Key { get; set; }
        public string Equipment_Key { get; set; }
        public string EMSPart_Key { get; set; }
        public decimal Quantity { get; set; }
        public string Description { get; set; }
        public string EMSPMMethod_Key { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<EMSHistory> EMSHistories { get; set; }
        public virtual EMSPart EMSPart { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
