//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSPart
    {
        public EMSPart()
        {
            this.EMSPartLists = new HashSet<EMSPartList>();
        }
    
        public string EMSPart_Key { get; set; }
        public string Inventory_Location_Key { get; set; }
        public string EMSLookupPartCategory_Key { get; set; }
        public string UOM_Key { get; set; }
        public string Vendor_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NameDesc { get; set; }
        public string MfgPartNum { get; set; }
        public string MfgPartNum2 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual EMSLookupPartCategory EMSLookupPartCategory { get; set; }
        public virtual UOM UOM { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual Inventory_Location Inventory_Location { get; set; }
        public virtual ICollection<EMSPartList> EMSPartLists { get; set; }
    }
}
