//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSPolicyDetail
    {
        public string EMSPolicyDetail_Key { get; set; }
        public string EMSPolicy_Key { get; set; }
        public string EMSPolicyMaintenance_Key { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual EMSPolicy EMSPolicy { get; set; }
        public virtual EMSPolicyMaintenance EMSPolicyMaintenance { get; set; }
    }
}
