//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSReadingHistory
    {
        public string EMSReadingHistory_Key { get; set; }
        public string Equipment_Key { get; set; }
        public string Employee_Key { get; set; }
        public string Department_Key { get; set; }
        public string ReadingSource { get; set; }
        public Nullable<System.DateTime> LastReadingDate { get; set; }
        public Nullable<int> LastReadingHours { get; set; }
        public Nullable<int> LastReadingMiles { get; set; }
        public Nullable<int> LifetimeTotalHours { get; set; }
        public Nullable<int> LifetimeTotalMiles { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
