//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSReadingValidation
    {
        public string EMSReadingValidation_Key { get; set; }
        public string Equipment_Key { get; set; }
        public string BatchNumber { get; set; }
        public string ReadingSource { get; set; }
        public Nullable<System.DateTime> ReadingDate { get; set; }
        public Nullable<int> ReadingHours { get; set; }
        public Nullable<int> ReadingMiles { get; set; }
        public Nullable<int> RolloverValueHours { get; set; }
        public Nullable<int> RolloverValueMiles { get; set; }
        public string Comment { get; set; }
        public byte InValid { get; set; }
        public byte Post { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
