//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSWorkOrder
    {
        public EMSWorkOrder()
        {
            this.EMSHistories = new HashSet<EMSHistory>();
            this.EMSWorkOrderDetails = new HashSet<EMSWorkOrderDetail>();
        }
    
        public string EMSWorkOrder_Key { get; set; }
        public string Equipment_Key { get; set; }
        public string EMSWorkOrderStatus_Key { get; set; }
        public string WorkOrderNumber { get; set; }
        public string Location_Key { get; set; }
        public Nullable<System.DateTime> DateTimeIn { get; set; }
        public Nullable<System.DateTime> DateTimeOut { get; set; }
        public Nullable<System.DateTime> DateTimeClosed { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<int> HoursAtService { get; set; }
        public Nullable<int> MilesAtService { get; set; }
        public string Description { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
        public byte PostedToMaintenanceHistory { get; set; }
    
        public virtual ICollection<EMSHistory> EMSHistories { get; set; }
        public virtual EMSWorkOrderStatu EMSWorkOrderStatu { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual ICollection<EMSWorkOrderDetail> EMSWorkOrderDetails { get; set; }
        public virtual Location Location { get; set; }
    }
}
