//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSWorkOrderDetail
    {
        public EMSWorkOrderDetail()
        {
            this.EMSHistories = new HashSet<EMSHistory>();
        }
    
        public string EMSWorkOrderDetail_Key { get; set; }
        public string EMSWorkOrder_Key { get; set; }
        public string EMSPolicyList_Key { get; set; }
        public string EMSTask_Key { get; set; }
        public string Employee_Key { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
        public Nullable<decimal> LaborQuantity { get; set; }
        public Nullable<decimal> LaborUnitCost { get; set; }
        public string Equipment_Key { get; set; }
        public Nullable<decimal> EquipmentUnitCost { get; set; }
        public Nullable<decimal> EquipmentQuantity { get; set; }
        public string EMSPart_Key { get; set; }
        public Nullable<decimal> EMSPartQuantity { get; set; }
        public string EMSPartDescription { get; set; }
        public Nullable<decimal> EMSPartCost { get; set; }
        public string PartUOM_Key { get; set; }
        public Nullable<decimal> OutsideServiceQuantity { get; set; }
        public string OutsideServiceDescription { get; set; }
        public Nullable<decimal> OutsideServiceCost { get; set; }
        public string ServiceDescription { get; set; }
        public Nullable<byte> Complete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
        public byte PostedToMaintenanceHistory { get; set; }
        public string EMSPMMethod_Key { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<EMSHistory> EMSHistories { get; set; }
        public virtual EMSPMMethod EMSPMMethod { get; set; }
        public virtual EMSTask EMSTask { get; set; }
        public virtual EMSWorkOrder EMSWorkOrder { get; set; }
    }
}
