//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.EMSDepartmentHistories = new HashSet<EMSDepartmentHistory>();
            this.EMSEmployeeHistories = new HashSet<EMSEmployeeHistory>();
            this.EMSHistories = new HashSet<EMSHistory>();
            this.EMSMaintEntries = new HashSet<EMSMaintEntry>();
            this.EMSPartLists = new HashSet<EMSPartList>();
            this.EMSPolicyLists = new HashSet<EMSPolicyList>();
            this.EMSReadingHistories = new HashSet<EMSReadingHistory>();
            this.EMSReadingUpdates = new HashSet<EMSReadingUpdate>();
            this.EMSReadingValidations = new HashSet<EMSReadingValidation>();
            this.EMSWorkOrders = new HashSet<EMSWorkOrder>();
            this.Transacts = new HashSet<Transact>();
            this.Transact_History = new HashSet<Transact_History>();
            this.EquipmentRates = new HashSet<EquipmentRate>();
            this.InventoryTransferDetails = new HashSet<InventoryTransferDetail>();
            this.TimeCards = new HashSet<TimeCard>();
            this.VMSSprayReportEquipments = new HashSet<VMSSprayReportEquipment>();
        }
    
        public string Equipment_Key { get; set; }
        public string ResourceClass_Key { get; set; }
        public string RelatedEquipment_Key { get; set; }
        public string Employee_Key { get; set; }
        public string Project_Key { get; set; }
        public string Department_Key { get; set; }
        public string EMSEquipmentStatus_Key { get; set; }
        public string Comments_Key { get; set; }
        public string EMSMeterClass_Key { get; set; }
        public string EMSEquipmentCondition_Key { get; set; }
        public string EMSMeterType_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NameDesc { get; set; }
        public string DescName { get; set; }
        public string Color { get; set; }
        public string AssetNumber { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Model_Year { get; set; }
        public string Engine { get; set; }
        public string EngineSerialNum { get; set; }
        public string EngineModelNum { get; set; }
        public string EngineArrangementNum { get; set; }
        public string EMSFuelType_Key { get; set; }
        public string Capacity { get; set; }
        public Nullable<System.DateTime> Purchase_Date { get; set; }
        public Nullable<System.DateTime> DisposeDate { get; set; }
        public Nullable<decimal> Purchase_Price { get; set; }
        public decimal SetUpCost { get; set; }
        public Nullable<decimal> SalvageValue { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public byte GASB34 { get; set; }
        public Nullable<decimal> Depreciation { get; set; }
        public Nullable<decimal> DepreciationThisYear { get; set; }
        public string DepreciationUOM { get; set; }
        public Nullable<int> Expected_Life { get; set; }
        public Nullable<System.DateTime> ReplacementDate { get; set; }
        public Nullable<decimal> ReplacementCost { get; set; }
        public string ReplacementCostMethod { get; set; }
        public Nullable<decimal> ReplacementCalcBegCost { get; set; }
        public Nullable<System.DateTime> ReplacementCalcBegDate { get; set; }
        public Nullable<decimal> CalculatedReplacementCostHours { get; set; }
        public Nullable<System.DateTime> CalculatedReplacementDateHours { get; set; }
        public Nullable<decimal> CalculatedReplacementCostMiles { get; set; }
        public Nullable<System.DateTime> CalculatedReplacementDateMiles { get; set; }
        public Nullable<int> ReplacementHours { get; set; }
        public Nullable<int> ReplacementMiles { get; set; }
        public Nullable<int> AverageAnnualHours { get; set; }
        public Nullable<int> AverageAnnualMiles { get; set; }
        public string Purchase_From { get; set; }
        public Nullable<int> MeterAtDeliveryHours { get; set; }
        public Nullable<int> OriginalMeterHours { get; set; }
        public Nullable<int> RolloverValueHours { get; set; }
        public Nullable<int> RolloverCountHours { get; set; }
        public Nullable<int> LifeTimeTotalHours { get; set; }
        public Nullable<int> MeterAtDeliveryMiles { get; set; }
        public Nullable<int> OriginalMeterMiles { get; set; }
        public Nullable<int> RolloverValueMiles { get; set; }
        public Nullable<int> RolloverCountMiles { get; set; }
        public Nullable<int> LifeTimeTotalMiles { get; set; }
        public string Serial_Number { get; set; }
        public string Model_Number { get; set; }
        public string License_Number { get; set; }
        public string Permit { get; set; }
        public Nullable<System.DateTime> PermitExpiration { get; set; }
        public byte IsInsured { get; set; }
        public string InsurancePolicyNumber { get; set; }
        public string EMSPMMethod_Key { get; set; }
        public Nullable<int> PMFrequency { get; set; }
        public Nullable<int> LastReadingMiles { get; set; }
        public Nullable<int> LastReadingHours { get; set; }
        public Nullable<System.DateTime> LastReadingDate { get; set; }
        public byte MilesRequired { get; set; }
        public byte HoursRequired { get; set; }
        public Nullable<int> WarningLevelHours { get; set; }
        public Nullable<int> WarningLevelMiles { get; set; }
        public Nullable<int> LastPM { get; set; }
        public Nullable<int> NextPMDue { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string NotUsed1 { get; set; }
        public string NotUsed2 { get; set; }
        public string NotUsed3 { get; set; }
        public string NotUsed4 { get; set; }
        public string NotUsed5 { get; set; }
        public int AttachedDocuments { get; set; }
        public byte VMSEquipment { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
        public string CRWResourceClassUVW_Key { get; set; }
    
        public virtual ICollection<EMSDepartmentHistory> EMSDepartmentHistories { get; set; }
        public virtual ICollection<EMSEmployeeHistory> EMSEmployeeHistories { get; set; }
        public virtual EMSEquipmentCondition EMSEquipmentCondition { get; set; }
        public virtual EMSEquipmentStatu EMSEquipmentStatu { get; set; }
        public virtual EMSFuelType EMSFuelType { get; set; }
        public virtual ICollection<EMSHistory> EMSHistories { get; set; }
        public virtual ICollection<EMSMaintEntry> EMSMaintEntries { get; set; }
        public virtual EMSMeterType EMSMeterType { get; set; }
        public virtual ICollection<EMSPartList> EMSPartLists { get; set; }
        public virtual EMSPMMethod EMSPMMethod { get; set; }
        public virtual ICollection<EMSPolicyList> EMSPolicyLists { get; set; }
        public virtual ICollection<EMSReadingHistory> EMSReadingHistories { get; set; }
        public virtual ICollection<EMSReadingUpdate> EMSReadingUpdates { get; set; }
        public virtual ICollection<EMSReadingValidation> EMSReadingValidations { get; set; }
        public virtual ICollection<EMSWorkOrder> EMSWorkOrders { get; set; }
        public virtual ResourceClass ResourceClass { get; set; }
        public virtual ICollection<Transact> Transacts { get; set; }
        public virtual ICollection<Transact_History> Transact_History { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<EquipmentRate> EquipmentRates { get; set; }
        public virtual ICollection<InventoryTransferDetail> InventoryTransferDetails { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
        public virtual ICollection<VMSSprayReportEquipment> VMSSprayReportEquipments { get; set; }
    }
}
