//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldPropTable
    {
        public string FieldPropTable_Key { get; set; }
        public string TableName { get; set; }
        public string TableDescription { get; set; }
        public string SecurityObject_Key { get; set; }
        public byte CRWPrimaryTable { get; set; }
        public string Module_Key { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
    }
}
