//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldPropUserSetting
    {
        public string FieldProp_Key { get; set; }
        public byte IsEnabled { get; set; }
        public byte IsRequired { get; set; }
        public System.DateTime DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    }
}
