//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterSysData
    {
        public FilterSysData()
        {
            this.FilterRPTSorts = new HashSet<FilterRPTSort>();
        }
    
        public string FilterSysData_Key { get; set; }
        public string SecurityObject_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string OriginalDescription { get; set; }
        public string Type { get; set; }
        public Nullable<byte> KeyField { get; set; }
        public Nullable<byte> UseDropDown { get; set; }
        public Nullable<byte> UseLikeOperator { get; set; }
        public string Sproc { get; set; }
        public string JoinSQL { get; set; }
        public byte IsRequired { get; set; }
        public byte AllowSort { get; set; }
        public byte NoFilter { get; set; }
        public string DefaultFilter { get; set; }
        public Nullable<int> DefaultFilterOrder { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<FilterRPTSort> FilterRPTSorts { get; set; }
        public virtual SecurityObject SecurityObject { get; set; }
    }
}
