//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterDetail
    {
        public string FilterDetail_Key { get; set; }
        public string FilterType { get; set; }
        public string TableName { get; set; }
        public string FilterName { get; set; }
        public string FieldName { get; set; }
        public string Description { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public string Operator1 { get; set; }
        public string Operator2 { get; set; }
        public string Group1 { get; set; }
        public string Group2 { get; set; }
        public string DataType { get; set; }
        public short KeyField { get; set; }
        public byte UseDropdown { get; set; }
        public byte UseNonUniqueList { get; set; }
        public byte UseLikeOperator { get; set; }
        public string SprocName { get; set; }
        public Nullable<int> RecordOrder { get; set; }
        public string EnglishWhere { get; set; }
        public string ForeignKey { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
    }
}
