//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public string Filter_Key { get; set; }
        public string FilterType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string TableName { get; set; }
        public string Type { get; set; }
        public byte KeyField { get; set; }
        public byte UseDropdown { get; set; }
        public byte UseNonUniqueList { get; set; }
        public byte UseLikeOperator { get; set; }
        public string SProcName { get; set; }
        public string SPROC { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    }
}
