//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterRPTSort
    {
        public string FilterRPTSort_Key { get; set; }
        public string FilterSysData_Key { get; set; }
        public string SecurityObject_Key { get; set; }
        public string SavedName { get; set; }
        public byte OrdinalPosition { get; set; }
        public byte SortAscending { get; set; }
        public string SecurityUser_Key { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    
        public virtual FilterSysData FilterSysData { get; set; }
        public virtual SecurityObject SecurityObject { get; set; }
    }
}
