//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterSavedData
    {
        public string FilterSavedData_Key { get; set; }
        public string SecurityObject_Key { get; set; }
        public string FilterSysData_Key { get; set; }
        public string SavedName { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public string Operator1 { get; set; }
        public string Operator2 { get; set; }
        public string Group1 { get; set; }
        public string Group2 { get; set; }
        public Nullable<int> RecordOrder { get; set; }
        public string EnglishWhere { get; set; }
        public string ForeignKey { get; set; }
        public byte IsRequired { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    
        public virtual SecurityObject SecurityObject { get; set; }
    }
}
