//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialMatrix
    {
        public string FinancialMatrix_Key { get; set; }
        public string Pay_Type_Key { get; set; }
        public string SupervisorCode { get; set; }
        public string UnionCode { get; set; }
        public string LeaveCode { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    }
}
