//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiscal
    {
        public Fiscal()
        {
            this.EquipmentRates = new HashSet<EquipmentRate>();
            this.RISSurfaceTypes = new HashSet<RISSurfaceType>();
            this.OH_Rates = new HashSet<OH_Rates>();
            this.PayVarianceDatas = new HashSet<PayVarianceData>();
            this.Projects = new HashSet<Project>();
            this.ResourceClassRates = new HashSet<ResourceClassRate>();
            this.TimeCards = new HashSet<TimeCard>();
            this.Transacts = new HashSet<Transact>();
            this.Transact_History = new HashSet<Transact_History>();
        }
    
        public string Fiscal_Key { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> Beg_Fiscal { get; set; }
        public Nullable<System.DateTime> End_Fiscal { get; set; }
        public string NameDesc { get; set; }
        public string DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<EquipmentRate> EquipmentRates { get; set; }
        public virtual ICollection<RISSurfaceType> RISSurfaceTypes { get; set; }
        public virtual ICollection<OH_Rates> OH_Rates { get; set; }
        public virtual ICollection<PayVarianceData> PayVarianceDatas { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<ResourceClassRate> ResourceClassRates { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
        public virtual ICollection<Transact> Transacts { get; set; }
        public virtual ICollection<Transact_History> Transact_History { get; set; }
    }
}
