//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public Form()
        {
            this.Required_Enabled_Fields = new HashSet<Required_Enabled_Fields>();
            this.UserDefinedFields = new HashSet<UserDefinedField>();
        }
    
        public string Form_Key { get; set; }
        public string Module_Key { get; set; }
        public string Form_Name { get; set; }
        public string Form_Description { get; set; }
        public string Table_Name { get; set; }
        public string DocumentCaption { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual ICollection<Required_Enabled_Fields> Required_Enabled_Fields { get; set; }
        public virtual ICollection<UserDefinedField> UserDefinedFields { get; set; }
    }
}
