//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelImportSchema
    {
        public int FuelImportSchema_Key { get; set; }
        public byte TextFileColumnIndex { get; set; }
        public string FileColumnValue { get; set; }
        public string TimecardFieldName { get; set; }
        public string GridCaption { get; set; }
        public Nullable<byte> Required { get; set; }
        public string RelatedKey { get; set; }
        public string County_Key { get; set; }
        public string Comment { get; set; }
    
        public virtual County County { get; set; }
    }
}
