//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GridConfig
    {
        public GridConfig()
        {
            this.GridConfigDetails = new HashSet<GridConfigDetail>();
        }
    
        public string GridConfig_Key { get; set; }
        public string Name { get; set; }
        public string SecurityObject_Key { get; set; }
        public byte SplitterPosition { get; set; }
        public byte CopyDownOn { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual SecurityObject SecurityObject { get; set; }
        public virtual ICollection<GridConfigDetail> GridConfigDetails { get; set; }
    }
}
