//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Receive
    {
        public string Inv_Receive_Key { get; set; }
        public string Inventory_Location_Key { get; set; }
        public Nullable<System.DateTime> Inv_Date { get; set; }
        public string Vendor_Key { get; set; }
        public string Activity_Key { get; set; }
        public string Tracking_Number { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price_Value { get; set; }
        public string Comments { get; set; }
        public bool Posted { get; set; }
        public byte PostToAPS { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Inventory_Location Inventory_Location { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
