//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryPhysicalCount
    {
        public string InventoryPhysicalCount_Key { get; set; }
        public string Inventory_Location_Key { get; set; }
        public decimal Quantity { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Inventory_Location Inventory_Location { get; set; }
    }
}
