//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Location
    {
        public Inventory_Location()
        {
            this.APSPayables = new HashSet<APSPayable>();
            this.APSTransacts = new HashSet<APSTransact>();
            this.EMSParts = new HashSet<EMSPart>();
            this.Inv_Receive = new HashSet<Inv_Receive>();
            this.Inv_Transact = new HashSet<Inv_Transact>();
            this.InventoryPhysicalCounts = new HashSet<InventoryPhysicalCount>();
            this.InventoryTransfers = new HashSet<InventoryTransfer>();
            this.TimeCards = new HashSet<TimeCard>();
            this.Transacts = new HashSet<Transact>();
            this.Transact_History = new HashSet<Transact_History>();
            this.VMSAgentProducts = new HashSet<VMSAgentProduct>();
            this.VMSSurfactants = new HashSet<VMSSurfactant>();
        }
    
        public string Inventory_Location_Key { get; set; }
        public string Inventory_Key { get; set; }
        public string Location_Key { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price_Value { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public string Bin { get; set; }
        public byte Active { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<APSPayable> APSPayables { get; set; }
        public virtual ICollection<APSTransact> APSTransacts { get; set; }
        public virtual ICollection<EMSPart> EMSParts { get; set; }
        public virtual ICollection<Inv_Receive> Inv_Receive { get; set; }
        public virtual ICollection<Inv_Transact> Inv_Transact { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual ICollection<InventoryPhysicalCount> InventoryPhysicalCounts { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<InventoryTransfer> InventoryTransfers { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
        public virtual ICollection<Transact> Transacts { get; set; }
        public virtual ICollection<Transact_History> Transact_History { get; set; }
        public virtual ICollection<VMSAgentProduct> VMSAgentProducts { get; set; }
        public virtual ICollection<VMSSurfactant> VMSSurfactants { get; set; }
    }
}
