//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransfer
    {
        public InventoryTransfer()
        {
            this.InventoryTransferDetails = new HashSet<InventoryTransferDetail>();
        }
    
        public string InventoryTransfer_Key { get; set; }
        public string Inventory_Key { get; set; }
        public string OldInventoryLocation_Key { get; set; }
        public string NewInventoryLocation_Key { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public bool Posted { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Inventory_Location Inventory_Location { get; set; }
        public virtual ICollection<InventoryTransferDetail> InventoryTransferDetails { get; set; }
    }
}
