//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransferDetail
    {
        public string InventoryTransferDetail_Key { get; set; }
        public string InventoryTransfer_Key { get; set; }
        public string Employee_Key { get; set; }
        public Nullable<decimal> LaborQuantity { get; set; }
        public Nullable<decimal> EquipmentQuantity { get; set; }
        public string Equipment_Key { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
        public Nullable<decimal> ServiceCost { get; set; }
        public string ServiceDescription { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual InventoryTransfer InventoryTransfer { get; set; }
    }
}
