//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRISRemoteExportTable
    {
        public int IRISRemoteExportTable_Key { get; set; }
        public string ObjectType { get; set; }
        public string ObjectName { get; set; }
        public Nullable<byte> HasFlagField { get; set; }
        public Nullable<byte> DeleteAfterUpdate { get; set; }
    }
}
