//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupValue
    {
        public LookupValue()
        {
            this.LookupValuesDetails = new HashSet<LookupValuesDetail>();
            this.UserDefinedFields = new HashSet<UserDefinedField>();
            this.UserDefinedFields1 = new HashSet<UserDefinedField>();
            this.UserDefinedFields2 = new HashSet<UserDefinedField>();
            this.UserDefinedFields3 = new HashSet<UserDefinedField>();
            this.UserDefinedFields4 = new HashSet<UserDefinedField>();
        }
    
        public string LookupValues_Key { get; set; }
        public string Description { get; set; }
        public string TableName { get; set; }
        public string SprocName { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
        public bool LoadOnlyInUserDefinedTables { get; set; }
    
        public virtual ICollection<LookupValuesDetail> LookupValuesDetails { get; set; }
        public virtual ICollection<UserDefinedField> UserDefinedFields { get; set; }
        public virtual ICollection<UserDefinedField> UserDefinedFields1 { get; set; }
        public virtual ICollection<UserDefinedField> UserDefinedFields2 { get; set; }
        public virtual ICollection<UserDefinedField> UserDefinedFields3 { get; set; }
        public virtual ICollection<UserDefinedField> UserDefinedFields4 { get; set; }
    }
}
