//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Forms = new HashSet<Form>();
            this.SecurityObjects = new HashSet<SecurityObject>();
        }
    
        public string Module_Key { get; set; }
        public string Short_Name { get; set; }
        public string Long_name { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<Form> Forms { get; set; }
        public virtual ICollection<SecurityObject> SecurityObjects { get; set; }
    }
}
