//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyIRISDetail
    {
        public string MyIRISDetail_Key { get; set; }
        public string MyIRIS_Key { get; set; }
        public string Modules_Key { get; set; }
        public string ObjectTitle { get; set; }
        public int ListOrder { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    }
}
