//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODOTPermit
    {
        public ODOTPermit()
        {
            this.ODOTPermitBridges = new HashSet<ODOTPermitBridge>();
        }
    
        public string ODOTPermit_Key { get; set; }
        public Nullable<System.DateTime> PermitDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string ODOTLookupIssuer_Key { get; set; }
        public int ODOTPermitNumber { get; set; }
        public string ODOTLookupCarrier_Key { get; set; }
        public string ODOTLookupCommodity_Key { get; set; }
        public Nullable<decimal> LoadLength { get; set; }
        public Nullable<decimal> LoadWidth { get; set; }
        public Nullable<decimal> LoadHeigth { get; set; }
        public Nullable<decimal> OverallLength { get; set; }
        public Nullable<int> TotalWeight { get; set; }
        public Nullable<int> NumberOfAxles { get; set; }
        public Nullable<int> FrontOverhang { get; set; }
        public Nullable<int> RearOverhang { get; set; }
        public Nullable<int> WeightTable { get; set; }
        public string StartingPoint { get; set; }
        public string Destination { get; set; }
        public string StartingAddress { get; set; }
        public string EndingAddress { get; set; }
        public string Route { get; set; }
        public string OtherRouteCondition { get; set; }
        public Nullable<byte> WeightAndSpacingNeeded { get; set; }
        public Nullable<decimal> AxleGroup1Weight { get; set; }
        public Nullable<decimal> AxleGroup2Weight { get; set; }
        public Nullable<decimal> AxleGroup3Weight { get; set; }
        public Nullable<decimal> AxleGroup4Weight { get; set; }
        public Nullable<decimal> AxleGroup5Weight { get; set; }
        public Nullable<decimal> AxleGroup6Weight { get; set; }
        public Nullable<decimal> AxleGroup7Weight { get; set; }
        public Nullable<decimal> AxleGroup8Weight { get; set; }
        public Nullable<decimal> AxleGroup9Weight { get; set; }
        public Nullable<decimal> AxleGroup10Weight { get; set; }
        public Nullable<decimal> AxleGroup11Weight { get; set; }
        public Nullable<decimal> AxleGroup12Weight { get; set; }
        public Nullable<decimal> AxleSpacing1 { get; set; }
        public Nullable<decimal> AxleSpacing2 { get; set; }
        public Nullable<decimal> AxleSpacing3 { get; set; }
        public Nullable<decimal> AxleSpacing4 { get; set; }
        public Nullable<decimal> AxleSpacing5 { get; set; }
        public Nullable<decimal> AxleSpacing6 { get; set; }
        public Nullable<decimal> AxleSpacing7 { get; set; }
        public Nullable<decimal> AxleSpacing8 { get; set; }
        public Nullable<decimal> AxleSpacing9 { get; set; }
        public Nullable<decimal> AxleSpacing10 { get; set; }
        public Nullable<decimal> AxleSpacing11 { get; set; }
        public Nullable<decimal> AxleSpacing12 { get; set; }
        public string OverweightCheckBy { get; set; }
        public string DirectorApproval_Key { get; set; }
        public string SecurityUser2_Key { get; set; }
        public Nullable<int> NumberPilotCarsFront { get; set; }
        public Nullable<int> NumberPilotCarsRear { get; set; }
        public Nullable<int> NumberOfPilotCarRequired_Key { get; set; }
        public Nullable<int> TotalTrips { get; set; }
        public byte RouteHeightPole { get; set; }
        public byte LegalWeight { get; set; }
        public byte LegalHeight { get; set; }
        public byte LegalWidth { get; set; }
        public byte LegalLength { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ODOTLookupCarrier ODOTLookupCarrier { get; set; }
        public virtual ODOTLookupCommodity ODOTLookupCommodity { get; set; }
        public virtual ODOTLookupIssuer ODOTLookupIssuer { get; set; }
        public virtual SecurityUser SecurityUser { get; set; }
        public virtual ICollection<ODOTPermitBridge> ODOTPermitBridges { get; set; }
    }
}
