//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OH_Rates
    {
        public string OH_Rates_Key { get; set; }
        public string OH_Class_Key { get; set; }
        public string Fiscal_Key { get; set; }
        public decimal OH_Percent { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Fiscal Fiscal { get; set; }
    }
}
