//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.APSBudgets = new HashSet<APSBudget>();
            this.APSPayables = new HashSet<APSPayable>();
            this.APSTransacts = new HashSet<APSTransact>();
            this.APSTransactAudits = new HashSet<APSTransactAudit>();
            this.ARSBudgets = new HashSet<ARSBudget>();
            this.ARSCanceledPayments = new HashSet<ARSCanceledPayment>();
            this.ARSInvoices = new HashSet<ARSInvoice>();
            this.ARSInvoiceApprovals = new HashSet<ARSInvoiceApproval>();
            this.ARSPayments = new HashSet<ARSPayment>();
        }
    
        public string Organization_Key { get; set; }
        public string OrganizationName { get; set; }
        public string NameDesc { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EMail { get; set; }
        public string Website { get; set; }
        public string UNCCallerID { get; set; }
        public byte[] Logo { get; set; }
        public string Comments { get; set; }
        public byte DefaultOrganization { get; set; }
        public string ARSInvoiceNumberPrefix { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<APSBudget> APSBudgets { get; set; }
        public virtual ICollection<APSPayable> APSPayables { get; set; }
        public virtual ICollection<APSTransact> APSTransacts { get; set; }
        public virtual ICollection<APSTransactAudit> APSTransactAudits { get; set; }
        public virtual ICollection<ARSBudget> ARSBudgets { get; set; }
        public virtual ICollection<ARSCanceledPayment> ARSCanceledPayments { get; set; }
        public virtual ICollection<ARSInvoice> ARSInvoices { get; set; }
        public virtual ICollection<ARSInvoiceApproval> ARSInvoiceApprovals { get; set; }
        public virtual ICollection<ARSPayment> ARSPayments { get; set; }
    }
}
