//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Type
    {
        public Pay_Type()
        {
            this.TimeAccruals = new HashSet<TimeAccrual>();
            this.TimeAccruals1 = new HashSet<TimeAccrual>();
            this.VMSSprayReportEmployees = new HashSet<VMSSprayReportEmployee>();
            this.PayVarianceDatas = new HashSet<PayVarianceData>();
            this.TimeCards = new HashSet<TimeCard>();
            this.Transacts = new HashSet<Transact>();
            this.Transact_History = new HashSet<Transact_History>();
        }
    
        public string Pay_Type_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NameDesc { get; set; }
        public string DescName { get; set; }
        public string PayRollCode { get; set; }
        public decimal Pay_Factor { get; set; }
        public byte Allocate { get; set; }
        public Nullable<decimal> FixedRate { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<TimeAccrual> TimeAccruals { get; set; }
        public virtual ICollection<TimeAccrual> TimeAccruals1 { get; set; }
        public virtual ICollection<VMSSprayReportEmployee> VMSSprayReportEmployees { get; set; }
        public virtual ICollection<PayVarianceData> PayVarianceDatas { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
        public virtual ICollection<Transact> Transacts { get; set; }
        public virtual ICollection<Transact_History> Transact_History { get; set; }
    }
}
