//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayVarianceData
    {
        public string PayVarianceData_Key { get; set; }
        public string Fiscal_Key { get; set; }
        public int MonthIndex { get; set; }
        public string Employee_Key { get; set; }
        public byte ExtraHelp { get; set; }
        public byte Supervisor { get; set; }
        public byte VariancePay { get; set; }
        public string Pay_Type_Key { get; set; }
        public Nullable<System.DateTime> Task_Date { get; set; }
        public decimal Quantity { get; set; }
        public double PayRate { get; set; }
        public double Pay_Factor { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Fiscal Fiscal { get; set; }
        public virtual Pay_Type Pay_Type { get; set; }
    }
}
