//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitType
    {
        public PermitType()
        {
            this.Permits = new HashSet<Permit>();
        }
    
        public string PermitType_Key { get; set; }
        public string Name { get; set; }
        public string ReportName { get; set; }
        public string County_Key { get; set; }
    
        public virtual ICollection<Permit> Permits { get; set; }
    }
}
