//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permit
    {
        public string Permit_Key { get; set; }
        public string PermitNumber { get; set; }
        public string AuthorizationNumber { get; set; }
        public string ApplicationNumber { get; set; }
        public string PermitType_Key { get; set; }
        public string PermitStatus_Key { get; set; }
        public string PermitTypeOfAccess_Key { get; set; }
        public string UOM_Key { get; set; }
        public string RISMaintenanceDistrict_Key { get; set; }
        public string SecurityUser2_Key { get; set; }
        public string IssuedByPosition { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string RISPlacement_Key { get; set; }
        public string Direction { get; set; }
        public string RoadName_Key { get; set; }
        public Nullable<decimal> Milepost { get; set; }
        public Nullable<decimal> BeginMilepost { get; set; }
        public Nullable<decimal> EndMilepost { get; set; }
        public string XRoadName_Key { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<decimal> SidewalkLength { get; set; }
        public Nullable<decimal> SidewalkWidth { get; set; }
        public string RISLookupCurb_Key { get; set; }
        public Nullable<decimal> CulvertDiameter { get; set; }
        public Nullable<decimal> CulvertLength { get; set; }
        public Nullable<decimal> CulvertDepth { get; set; }
        public Nullable<decimal> DrivewayLength { get; set; }
        public Nullable<decimal> DrivewayWidth { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> Radius { get; set; }
        public Nullable<decimal> Angle { get; set; }
        public Nullable<decimal> Slope { get; set; }
        public string Dimension { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<decimal> OffsetDistance { get; set; }
        public Nullable<decimal> SetbackWidth { get; set; }
        public string MeasuredFrom { get; set; }
        public Nullable<decimal> DistanceToDitch { get; set; }
        public Nullable<decimal> TopOfAccessDistanceFromTrafficLane { get; set; }
        public Nullable<decimal> MinimumBelowEdgeOfTrafficLane { get; set; }
        public Nullable<decimal> DistanceFromTrafficLane { get; set; }
        public Nullable<decimal> MinimumSightDistanceLeft { get; set; }
        public Nullable<decimal> MinimumSightDistanceRight { get; set; }
        public string TaxlotNumber { get; set; }
        public string Township { get; set; }
        public string Range { get; set; }
        public string Section { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> PermitReturned { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public byte CertificateOfInsurance { get; set; }
        public byte NeverExpires { get; set; }
        public string DescriptionOfWork { get; set; }
        public string LocationOfWork { get; set; }
        public string NearestLandMark { get; set; }
        public string SurfaceType { get; set; }
        public string DrawingNumber { get; set; }
        public Nullable<decimal> SlopeAccessFeetFromTrafficLane { get; set; }
        public Nullable<decimal> SlopeAccessPercentFromTrafficLane { get; set; }
        public Nullable<decimal> ClearanceFeet { get; set; }
        public string WorkBeingPerformedBy { get; set; }
        public Nullable<byte> InsuranceProvided { get; set; }
        public Nullable<byte> TwoSetsOfPlansProvided { get; set; }
        public Nullable<decimal> BondGuaranteeAmount { get; set; }
        public string PermitFeeType_Key { get; set; }
        public string SpecialProvisions { get; set; }
        public Nullable<System.DateTime> PermissionGrantedDate { get; set; }
        public string WorkOrderNumber { get; set; }
        public string Comment { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerLastName { get; set; }
        public string OwnerInitial { get; set; }
        public string OwnerFullName { get; set; }
        public string OwnerAddress1 { get; set; }
        public string OwnerAddress2 { get; set; }
        public string OwnerHomePhone { get; set; }
        public string OwnerWorkPhone { get; set; }
        public string OwnerEmail { get; set; }
        public string OwnerCity { get; set; }
        public string OwnerState { get; set; }
        public string OwnerZip { get; set; }
        public string OwnerCityStateZip { get; set; }
        public string SiteFirstName { get; set; }
        public string SiteLastName { get; set; }
        public string SiteInitial { get; set; }
        public string SiteFullName { get; set; }
        public string SiteAddress1 { get; set; }
        public string SiteAddress2 { get; set; }
        public string SiteHomePhone { get; set; }
        public string SiteWorkPhone { get; set; }
        public string SiteEmail { get; set; }
        public string SiteCity { get; set; }
        public string SiteState { get; set; }
        public string SiteZip { get; set; }
        public string SiteCityStateZip { get; set; }
        public string ContractorCompanyName { get; set; }
        public string ContractorContact { get; set; }
        public string ContractorContactJobTitle { get; set; }
        public string FieldSupervisorName { get; set; }
        public string ContractorAddress1 { get; set; }
        public string ContractorAddress2 { get; set; }
        public string ContractorCity { get; set; }
        public string ContractorState { get; set; }
        public string ContractorZip { get; set; }
        public string ContractorCityStateZip { get; set; }
        public string ContractorPhone { get; set; }
        public string ContractorMobile { get; set; }
        public string ContractorFax { get; set; }
        public string ContractorEmail { get; set; }
        public string ContractorNumber { get; set; }
        public string Applicant { get; set; }
        public string ApplicantPosition { get; set; }
        public string ApplicantCompany { get; set; }
        public string ApplicantAddress { get; set; }
        public string ApplicantCity { get; set; }
        public string ApplicantState { get; set; }
        public string ApplicantZip { get; set; }
        public string ApplicantCityStateZip { get; set; }
        public string ApplicantPhone { get; set; }
        public string ApplicantMobile { get; set; }
        public string ApplicantFax { get; set; }
        public string ApplicantEmail { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual PermitFeeType PermitFeeType { get; set; }
        public virtual PermitStatu PermitStatu { get; set; }
        public virtual PermitType PermitType { get; set; }
        public virtual PermitTypeOfAccess PermitTypeOfAccess { get; set; }
        public virtual RISLookupCurb RISLookupCurb { get; set; }
        public virtual RISMaintenanceDistrict RISMaintenanceDistrict { get; set; }
        public virtual RoadName RoadName { get; set; }
        public virtual RoadName RoadName1 { get; set; }
        public virtual SecurityUser SecurityUser { get; set; }
        public virtual SecurityUser SecurityUser1 { get; set; }
        public virtual UOM UOM { get; set; }
    }
}
