//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.APSPayables = new HashSet<APSPayable>();
            this.CrewSheets = new HashSet<CrewSheet>();
            this.Roads = new HashSet<Road>();
            this.VMSConfigs = new HashSet<VMSConfig>();
            this.VMSPURSReports = new HashSet<VMSPURSReport>();
            this.VMSSprayReports = new HashSet<VMSSprayReport>();
            this.Projects = new HashSet<Project>();
            this.TimeCards = new HashSet<TimeCard>();
            this.Transacts = new HashSet<Transact>();
            this.Transact_History = new HashSet<Transact_History>();
        }
    
        public string Program_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NameDesc { get; set; }
        public string DescName { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
        public bool IsSystemData { get; set; }
    
        public virtual ICollection<APSPayable> APSPayables { get; set; }
        public virtual ICollection<CrewSheet> CrewSheets { get; set; }
        public virtual ICollection<Road> Roads { get; set; }
        public virtual ICollection<VMSConfig> VMSConfigs { get; set; }
        public virtual ICollection<VMSPURSReport> VMSPURSReports { get; set; }
        public virtual ICollection<VMSSprayReport> VMSSprayReports { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
        public virtual ICollection<Transact> Transacts { get; set; }
        public virtual ICollection<Transact_History> Transact_History { get; set; }
    }
}
