//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectResourceItemBillRate
    {
        public string ProjectResourceItemBillRate_Key { get; set; }
        public string Project_Key { get; set; }
        public string ResourceClass_Key { get; set; }
        public decimal Rate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ResourceClass ResourceClass { get; set; }
    }
}
