//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public string Rating_Key { get; set; }
        public string Rating1 { get; set; }
        public string Description { get; set; }
        public System.DateTime DateStamp { get; set; }
        public string User_Key { get; set; }
    }
}
