//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportBatchReport
    {
        public int ReportBatchReport_Key { get; set; }
        public byte[] CRWMgr { get; set; }
        public bool Invalid { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> LastRunDate { get; set; }
        public int TimesRun { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int ReportBatch_Key { get; set; }
    }
}
