//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportOption
    {
        public int ReportOption_Key { get; set; }
        public string SecurityObject_Key { get; set; }
        public string CheckBox1 { get; set; }
        public string CheckBox2 { get; set; }
        public string CheckBox3 { get; set; }
        public string CheckBox4 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual SecurityObject SecurityObject { get; set; }
    }
}
