//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Required_Enabled_Fields
    {
        public string Required_Enabled_Fields_Key { get; set; }
        public string Form_Key { get; set; }
        public string Field_Name { get; set; }
        public string Data_Field { get; set; }
        public bool Enabled { get; set; }
        public bool Required { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
