//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_Type
    {
        public Resource_Type()
        {
            this.APSPayables = new HashSet<APSPayable>();
            this.ARSInvoiceApprovals = new HashSet<ARSInvoiceApproval>();
            this.ARSInvoiceDetails = new HashSet<ARSInvoiceDetail>();
            this.ResourceClasses = new HashSet<ResourceClass>();
            this.Transacts = new HashSet<Transact>();
            this.Transact_History = new HashSet<Transact_History>();
        }
    
        public string Resource_Type_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NameDesc { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<APSPayable> APSPayables { get; set; }
        public virtual ICollection<ARSInvoiceApproval> ARSInvoiceApprovals { get; set; }
        public virtual ICollection<ARSInvoiceDetail> ARSInvoiceDetails { get; set; }
        public virtual ICollection<ResourceClass> ResourceClasses { get; set; }
        public virtual ICollection<Transact> Transacts { get; set; }
        public virtual ICollection<Transact_History> Transact_History { get; set; }
    }
}
