//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISADT
    {
        public string RISADT_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal BeginMilepost { get; set; }
        public decimal EndMilepost { get; set; }
        public string BeginDescription { get; set; }
        public string EndDescription { get; set; }
        public Nullable<System.DateTime> LastReadingDate { get; set; }
        public Nullable<decimal> Milepost { get; set; }
        public Nullable<double> UnadjustedADT { get; set; }
        public Nullable<double> AdjustedADT { get; set; }
        public Nullable<double> PercentTrucks { get; set; }
        public Nullable<int> DaysCounted { get; set; }
        public string CounterIDNumber { get; set; }
        public string Comments { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Flag { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Road Road { get; set; }
    }
}
