//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISApproach
    {
        public string RISApproach_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal Milepost { get; set; }
        public string RISLookupApproachPlacement_Key { get; set; }
        public string RISLookupApproachType_Key { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<byte> Culvert { get; set; }
        public string RISLookupApproachSurface_Key { get; set; }
        public string PermitNumber { get; set; }
        public Nullable<System.DateTime> PermitDate { get; set; }
        public string Comments { get; set; }
        public string ApplicantName { get; set; }
        public string PhysicalAddress { get; set; }
        public string Township { get; set; }
        public string Range { get; set; }
        public string Section { get; set; }
        public string TaxlotNumber { get; set; }
        public string PermitStatus { get; set; }
        public Nullable<System.DateTime> TemporaryPermitExpiration { get; set; }
        public byte FinalInspectionDue { get; set; }
        public Nullable<double> XCoordinate { get; set; }
        public Nullable<double> YCoordinate { get; set; }
        public Nullable<double> ZCoordinate { get; set; }
        public System.Data.Spatial.DbGeometry GISLocation { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Flag { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISLookupApproachPlacement RISLookupApproachPlacement { get; set; }
        public virtual RISLookupApproachSurface RISLookupApproachSurface { get; set; }
        public virtual RISLookupApproachType RISLookupApproachType { get; set; }
        public virtual Road Road { get; set; }
    }
}
