//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISBridge
    {
        public string RISBridge_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal Milepost { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Length { get; set; }
        public string RISLookupBridgePlacement_Key { get; set; }
        public Nullable<double> SufficiencyRate { get; set; }
        public Nullable<double> Sidewalkwidth { get; set; }
        public Nullable<double> SidewalkWidthRight { get; set; }
        public Nullable<double> SidewalkWidthLeft { get; set; }
        public Nullable<double> RoadwayWidth { get; set; }
        public Nullable<double> ApproachWidth { get; set; }
        public Nullable<double> DeckWidth { get; set; }
        public Nullable<short> NumberofSpans { get; set; }
        public string NBI { get; set; }
        public string CountyBridgeNumber { get; set; }
        public string PriorNumber { get; set; }
        public string BridgeName { get; set; }
        public Nullable<System.DateTime> LastInspectionDate { get; set; }
        public Nullable<short> YearConstructed { get; set; }
        public Nullable<short> LifeLeft { get; set; }
        public Nullable<byte> Lifeline { get; set; }
        public string RISLookupBridgeConstraint_Key { get; set; }
        public string RISLookupBridgeConstraint2_Key { get; set; }
        public string RISLookupBridgeConstraint3_Key { get; set; }
        public string RISLookupBridgeConstraint4_Key { get; set; }
        public Nullable<double> WeightLimit { get; set; }
        public Nullable<double> HeightLimit { get; set; }
        public Nullable<double> SpeedLimit { get; set; }
        public string RISLookupBridgeFeature_Key { get; set; }
        public string Bodyname { get; set; }
        public string RISLookupBridgeMaterial_Key { get; set; }
        public string Comments { get; set; }
        public Nullable<double> ADT { get; set; }
        public Nullable<System.DateTime> ADTDate { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> SpanLength1 { get; set; }
        public Nullable<double> SpanLength2 { get; set; }
        public Nullable<double> SpanLength3 { get; set; }
        public Nullable<double> SpanLength4 { get; set; }
        public Nullable<double> SpanLength5 { get; set; }
        public Nullable<double> SpanLength6 { get; set; }
        public Nullable<double> SpanLength7 { get; set; }
        public string Stringers { get; set; }
        public string Deck { get; set; }
        public string Abutment { get; set; }
        public byte LoadRated { get; set; }
        public byte Posted { get; set; }
        public byte AsBuiltDrawings { get; set; }
        public string TRS { get; set; }
        public Nullable<double> SeismicPriority { get; set; }
        public Nullable<double> MaxAllowTandemAxleLoad { get; set; }
        public Nullable<double> MaxAllowTridemAxleLoad { get; set; }
        public Nullable<double> ControllingLoad { get; set; }
        public Nullable<double> MaximumLoad { get; set; }
        public Nullable<double> Type3TruckTotalWeight { get; set; }
        public Nullable<double> Type3TruckWeightOnBridge { get; set; }
        public Nullable<double> Type3S2TruckTotalWeight { get; set; }
        public Nullable<double> Type3S2TruckWeightOnBridge { get; set; }
        public Nullable<double> Type33TruckTotalWeight { get; set; }
        public Nullable<double> Type33TruckWeightOnBridge { get; set; }
        public string Type3CriticalMember { get; set; }
        public string Type3S2CriticalMember { get; set; }
        public string Type33CriticalMember { get; set; }
        public string GeneralFailureType { get; set; }
        public Nullable<byte> PontisReport { get; set; }
        public Nullable<byte> CountyInspection { get; set; }
        public string ApproximateLocation { get; set; }
        public string MilepointFrom { get; set; }
        public byte Active { get; set; }
        public Nullable<double> XCoordinate { get; set; }
        public Nullable<double> YCoordinate { get; set; }
        public Nullable<double> ZCoordinate { get; set; }
        public System.Data.Spatial.DbGeometry GISLocation { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISLookupBridgeConstraint RISLookupBridgeConstraint { get; set; }
        public virtual RISLookupBridgeConstraint RISLookupBridgeConstraint1 { get; set; }
        public virtual RISLookupBridgeConstraint RISLookupBridgeConstraint2 { get; set; }
        public virtual RISLookupBridgeConstraint RISLookupBridgeConstraint3 { get; set; }
        public virtual RISLookupBridgeFeature RISLookupBridgeFeature { get; set; }
        public virtual RISLookupBridgeMaterial RISLookupBridgeMaterial { get; set; }
        public virtual RISLookupBridgePlacement RISLookupBridgePlacement { get; set; }
        public virtual Road Road { get; set; }
    }
}
