//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISCatchBasinHistory
    {
        public string RISCatchBasinHistory_Key { get; set; }
        public string RISCatchBasin_Key { get; set; }
        public Nullable<System.DateTime> HistoryDate { get; set; }
        public string RISLookupCatchBasinHistoryAction_Key { get; set; }
        public string InspectedBy { get; set; }
        public string RISLookupCondition_Key { get; set; }
        public string RISLookupCatchBasinHistoryGrateMaintenance_Key { get; set; }
        public string RISLookupCatchBasinHistoryVaultMaintenance_Key { get; set; }
        public string RISLookupCatchBasinHistoryOutFlowMaintenance_Key { get; set; }
        public string RISLookupCatchBasinHistoryRequiredRepair_Key { get; set; }
        public Nullable<System.DateTime> WorkOrderIssueDate { get; set; }
        public Nullable<System.DateTime> WorkOrderCompleteDate { get; set; }
        public string WorkOrderCompletedBy { get; set; }
        public string RISLookupCatchBasinHistoryDisposalLocation_Key { get; set; }
        public string Comment { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISCatchBasin RISCatchBasin { get; set; }
        public virtual RISLookupCatchBasinHistoryAction RISLookupCatchBasinHistoryAction { get; set; }
        public virtual RISLookupCatchBasinHistoryDisposalLocation RISLookupCatchBasinHistoryDisposalLocation { get; set; }
        public virtual RISLookupCatchBasinHistoryGrateMaintenance RISLookupCatchBasinHistoryGrateMaintenance { get; set; }
        public virtual RISLookupCatchBasinHistoryOutflowMaintenance RISLookupCatchBasinHistoryOutflowMaintenance { get; set; }
        public virtual RISLookupCatchBasinHistoryRequiredRepair RISLookupCatchBasinHistoryRequiredRepair { get; set; }
        public virtual RISLookupCatchBasinHistoryVaultMaintenance RISLookupCatchBasinHistoryVaultMaintenance { get; set; }
        public virtual RISLookupCondition RISLookupCondition { get; set; }
    }
}
