//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISFeatureVariance
    {
        public int RISFeatureVariance_Key { get; set; }
        public string Road_Key { get; set; }
        public string TableName { get; set; }
        public string Variance { get; set; }
    }
}
