//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISGuardRail
    {
        public RISGuardRail()
        {
            this.RISGuardRailHistories = new HashSet<RISGuardRailHistory>();
        }
    
        public string RISGuardRail_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal BeginMilepost { get; set; }
        public decimal EndMilepost { get; set; }
        public string RISLookupGuardRailPlacement_Key { get; set; }
        public string RISLookupBarrier_Key { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Offset { get; set; }
        public Nullable<double> Height { get; set; }
        public string RISLookupGuardRailPost_Key { get; set; }
        public string RISLookupPostSize_Key { get; set; }
        public string RISLookupGuardRailBeginTreatment_Key { get; set; }
        public string RISLookupGuardRailEndTreatment_Key { get; set; }
        public Nullable<short> NumberOfPosts { get; set; }
        public Nullable<short> NumberOfRails { get; set; }
        public string RISLookupGuardRailBlockType_Key { get; set; }
        public string RISLookupGuardRailBlockSize_Key { get; set; }
        public Nullable<short> NumberOfBlocks { get; set; }
        public Nullable<byte> Delineators { get; set; }
        public string BeginDelineatorType_Key { get; set; }
        public string EndDelineatorType_Key { get; set; }
        public Nullable<double> GISOffsetPoint { get; set; }
        public string Comments { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Flag { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISLookupBarrier RISLookupBarrier { get; set; }
        public virtual RISLookupDelineatorType RISLookupDelineatorType { get; set; }
        public virtual RISLookupDelineatorType RISLookupDelineatorType1 { get; set; }
        public virtual RISLookupGuardRailBeginTreatment RISLookupGuardRailBeginTreatment { get; set; }
        public virtual RISLookupGuardRailBlockSize RISLookupGuardRailBlockSize { get; set; }
        public virtual RISLookupGuardRailBlockType RISLookupGuardRailBlockType { get; set; }
        public virtual RISLookupGuardRailEndTreatment RISLookupGuardRailEndTreatment { get; set; }
        public virtual RISLookupGuardRailPlacement RISLookupGuardRailPlacement { get; set; }
        public virtual RISLookupGuardRailPost RISLookupGuardRailPost { get; set; }
        public virtual RISLookupPostSize RISLookupPostSize { get; set; }
        public virtual Road Road { get; set; }
        public virtual ICollection<RISGuardRailHistory> RISGuardRailHistories { get; set; }
    }
}
