//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISGate
    {
        public RISGate()
        {
            this.RISGateHistories = new HashSet<RISGateHistory>();
        }
    
        public string RISGate_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal Milepost { get; set; }
        public string RISLookupGate_Key { get; set; }
        public Nullable<double> Width { get; set; }
        public string RISLookupGateMaterial_Key { get; set; }
        public string RISLookupGateBaseMaterial_Key { get; set; }
        public byte PermitIssued { get; set; }
        public Nullable<System.DateTime> ConditionDate { get; set; }
        public string RISLookupCondition_Key { get; set; }
        public string RISLookupGateOwner_Key { get; set; }
        public string RISLookupGateManufacture_Key { get; set; }
        public Nullable<byte> NumberOfSections { get; set; }
        public string RISLookupGateWing_Key { get; set; }
        public Nullable<decimal> Section1Length { get; set; }
        public Nullable<decimal> Section1Width { get; set; }
        public Nullable<decimal> Section2Length { get; set; }
        public Nullable<decimal> Section2Width { get; set; }
        public Nullable<byte> ObjectMarker { get; set; }
        public Nullable<short> MinimumSightDistance { get; set; }
        public Nullable<byte> CattleGuardRequired { get; set; }
        public string RISLookupSurface_Key { get; set; }
        public string Comments { get; set; }
        public Nullable<double> XCoordinate { get; set; }
        public Nullable<double> YCoordinate { get; set; }
        public Nullable<double> ZCoordinate { get; set; }
        public System.Data.Spatial.DbGeometry GISLocation { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Flag { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISLookupCondition RISLookupCondition { get; set; }
        public virtual RISLookupGate RISLookupGate { get; set; }
        public virtual RISLookupGateBaseMaterial RISLookupGateBaseMaterial { get; set; }
        public virtual RISLookupGateManufacture RISLookupGateManufacture { get; set; }
        public virtual RISLookupGateMaterial RISLookupGateMaterial { get; set; }
        public virtual RISLookupGateOwner RISLookupGateOwner { get; set; }
        public virtual RISLookupGateWing RISLookupGateWing { get; set; }
        public virtual RISLookupSurface RISLookupSurface { get; set; }
        public virtual Road Road { get; set; }
        public virtual ICollection<RISGateHistory> RISGateHistories { get; set; }
    }
}
