//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISIntersection
    {
        public string RISIntersection_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal Milepost { get; set; }
        public string RISLookupIntersectionPlacement_Key { get; set; }
        public string XRoadNumber { get; set; }
        public Nullable<double> XMilepost { get; set; }
        public string XRoadName { get; set; }
        public string XRoadType { get; set; }
        public string XRoadDirection { get; set; }
        public Nullable<double> Xwidth { get; set; }
        public string RISLookupIntersectionRoadUse_Key { get; set; }
        public string Comments { get; set; }
        public Nullable<double> XCoordinate { get; set; }
        public Nullable<double> YCoordinate { get; set; }
        public Nullable<double> ZCoordinate { get; set; }
        public System.Data.Spatial.DbGeometry GISLocation { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Flag { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISLookupIntersectionPlacement RISLookupIntersectionPlacement { get; set; }
        public virtual RISLookupIntersectionRoadUse RISLookupIntersectionRoadUse { get; set; }
        public virtual Road Road { get; set; }
    }
}
