//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISLookupBridgeConstraint
    {
        public RISLookupBridgeConstraint()
        {
            this.RISBridges = new HashSet<RISBridge>();
            this.RISBridges1 = new HashSet<RISBridge>();
            this.RISBridges2 = new HashSet<RISBridge>();
            this.RISBridges3 = new HashSet<RISBridge>();
        }
    
        public string RISLookupBridgeConstraint_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NameDesc { get; set; }
        public string DescName { get; set; }
        public bool IsSystemData { get; set; }
    
        public virtual ICollection<RISBridge> RISBridges { get; set; }
        public virtual ICollection<RISBridge> RISBridges1 { get; set; }
        public virtual ICollection<RISBridge> RISBridges2 { get; set; }
        public virtual ICollection<RISBridge> RISBridges3 { get; set; }
    }
}
