//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISLevee
    {
        public RISLevee()
        {
            this.RISLeveeHistories = new HashSet<RISLeveeHistory>();
        }
    
        public string RISLevee_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal BeginMilepost { get; set; }
        public decimal EndMilepost { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string Name { get; set; }
        public string RISLookupLeveeBankPlacement_Key { get; set; }
        public string RISLookupLeveeOverAllConditionUVW_Key { get; set; }
        public Nullable<System.DateTime> LastInspectionDate { get; set; }
        public Nullable<double> AverageProtectionHeight { get; set; }
        public string Comment { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISLookupLeveeBankPlacement RISLookupLeveeBankPlacement { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating { get; set; }
        public virtual Road Road { get; set; }
        public virtual ICollection<RISLeveeHistory> RISLeveeHistories { get; set; }
    }
}
