//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISLeveeHistory
    {
        public string RISLeveeHistory_Key { get; set; }
        public string RISLevee_Key { get; set; }
        public Nullable<System.DateTime> HistoryDate { get; set; }
        public string RISLookupLeveeHistoryAction_Key { get; set; }
        public string RISLookupLeveeOverAllConditionUVW_Key { get; set; }
        public string Comment { get; set; }
        public string RISLookupLeveeOperationManualUVW_Key { get; set; }
        public string RISLookupLeveeEmergencySuppliesUVW_Key { get; set; }
        public string RISLookupLeveeFloodPreparednessUVW_Key { get; set; }
        public string RISLookupLeveeVegetationGrowthUVW_Key { get; set; }
        public string RISLookupLeveeEncroachmentsUVW_Key { get; set; }
        public string RISLookupLeveeSlopeStabilityUVW_Key { get; set; }
        public string RISLookupLeveeErosionUVW_Key { get; set; }
        public string RISLookupLeveeSettlementUVW_Key { get; set; }
        public string RISLookupLeveeDepressionRuttingUVW_Key { get; set; }
        public string RISLookupLeveeCrackingUVW_Key { get; set; }
        public string RISLookupLeveeAnimalControlUVW_Key { get; set; }
        public string RISLookupLeveeRiprapRevetmentsBankProtectionUVW_Key { get; set; }
        public string RISLookupLeveeRevetmentsOtherThanRiprapUVW_Key { get; set; }
        public string RISLookupLeveeSeepageUVW_Key { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISLevee RISLevee { get; set; }
        public virtual RISLookupLeveeHistoryAction RISLookupLeveeHistoryAction { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating1 { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating2 { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating3 { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating4 { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating5 { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating6 { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating7 { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating8 { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating9 { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating10 { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating11 { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating12 { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating13 { get; set; }
        public virtual RISLookupLeveeRating RISLookupLeveeRating14 { get; set; }
    }
}
