//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISLocationReference
    {
        public RISLocationReference()
        {
            this.RISStripMapHeaders = new HashSet<RISStripMapHeader>();
            this.RISLocationReferenceTables = new HashSet<RISLocationReferenceTable>();
            this.RISLocationReferenceDatas = new HashSet<RISLocationReferenceData>();
        }
    
        public string RISLocationReference_Key { get; set; }
        public string Name { get; set; }
        public byte StripMap { get; set; }
        public string FromRoad_Key { get; set; }
        public string ToRoad_Key { get; set; }
        public Nullable<System.DateTime> LastBuilt { get; set; }
        public Nullable<System.DateTime> LastPrinted { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<RISStripMapHeader> RISStripMapHeaders { get; set; }
        public virtual ICollection<RISLocationReferenceTable> RISLocationReferenceTables { get; set; }
        public virtual ICollection<RISLocationReferenceData> RISLocationReferenceDatas { get; set; }
    }
}
