//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISLookupManholePurpose
    {
        public RISLookupManholePurpose()
        {
            this.RISManHoles = new HashSet<RISManHole>();
            this.RISManHoles1 = new HashSet<RISManHole>();
            this.RISManHoles2 = new HashSet<RISManHole>();
            this.RISManHoles3 = new HashSet<RISManHole>();
            this.RISManHoles4 = new HashSet<RISManHole>();
            this.RISManHoles5 = new HashSet<RISManHole>();
        }
    
        public string RISLookupManholePurpose_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NameDesc { get; set; }
        public string DescName { get; set; }
        public bool IsSystemData { get; set; }
    
        public virtual ICollection<RISManHole> RISManHoles { get; set; }
        public virtual ICollection<RISManHole> RISManHoles1 { get; set; }
        public virtual ICollection<RISManHole> RISManHoles2 { get; set; }
        public virtual ICollection<RISManHole> RISManHoles3 { get; set; }
        public virtual ICollection<RISManHole> RISManHoles4 { get; set; }
        public virtual ICollection<RISManHole> RISManHoles5 { get; set; }
    }
}
