//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISLookupCondition
    {
        public RISLookupCondition()
        {
            this.RISBikeFacilities = new HashSet<RISBikeFacility>();
            this.RISCatchBasinHistories = new HashSet<RISCatchBasinHistory>();
            this.RISCurbs = new HashSet<RISCurb>();
            this.RISDitches = new HashSet<RISDitch>();
            this.RISGates = new HashSet<RISGate>();
            this.RISGateHistories = new HashSet<RISGateHistory>();
            this.RISGuardRailHistories = new HashSet<RISGuardRailHistory>();
            this.RISManHoles = new HashSet<RISManHole>();
            this.RISManHoleHistories = new HashSet<RISManHoleHistory>();
            this.RISSigns = new HashSet<RISSign>();
            this.RISSigns1 = new HashSet<RISSign>();
            this.RISSignHistories = new HashSet<RISSignHistory>();
            this.RISSignHistories1 = new HashSet<RISSignHistory>();
            this.RISSignHistoryAudits = new HashSet<RISSignHistoryAudit>();
            this.RISSignHistoryAudits1 = new HashSet<RISSignHistoryAudit>();
            this.RISWalks = new HashSet<RISWalk>();
            this.RISWheelChairs = new HashSet<RISWheelChair>();
        }
    
        public string RISLookupCondition_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NameDesc { get; set; }
        public string DescName { get; set; }
        public bool IsSystemData { get; set; }
    
        public virtual ICollection<RISBikeFacility> RISBikeFacilities { get; set; }
        public virtual ICollection<RISCatchBasinHistory> RISCatchBasinHistories { get; set; }
        public virtual ICollection<RISCurb> RISCurbs { get; set; }
        public virtual ICollection<RISDitch> RISDitches { get; set; }
        public virtual ICollection<RISGate> RISGates { get; set; }
        public virtual ICollection<RISGateHistory> RISGateHistories { get; set; }
        public virtual ICollection<RISGuardRailHistory> RISGuardRailHistories { get; set; }
        public virtual ICollection<RISManHole> RISManHoles { get; set; }
        public virtual ICollection<RISManHoleHistory> RISManHoleHistories { get; set; }
        public virtual ICollection<RISSign> RISSigns { get; set; }
        public virtual ICollection<RISSign> RISSigns1 { get; set; }
        public virtual ICollection<RISSignHistory> RISSignHistories { get; set; }
        public virtual ICollection<RISSignHistory> RISSignHistories1 { get; set; }
        public virtual ICollection<RISSignHistoryAudit> RISSignHistoryAudits { get; set; }
        public virtual ICollection<RISSignHistoryAudit> RISSignHistoryAudits1 { get; set; }
        public virtual ICollection<RISWalk> RISWalks { get; set; }
        public virtual ICollection<RISWheelChair> RISWheelChairs { get; set; }
    }
}
