//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISManHole
    {
        public RISManHole()
        {
            this.RISManHoleHistories = new HashSet<RISManHoleHistory>();
        }
    
        public string RISManhole_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal Milepost { get; set; }
        public string RISLookupManholePlacement_Key { get; set; }
        public Nullable<double> Offset { get; set; }
        public string ManholeVaultID { get; set; }
        public string RISLookupManholeMaterial_Key { get; set; }
        public string RISLookupManholePurpose_Key { get; set; }
        public string RISLookupManholePurpose2_Key { get; set; }
        public string RISLookupManholePurpose3_Key { get; set; }
        public string RISLookupManholePurpose4_Key { get; set; }
        public string RISLookupManholePurpose5_Key { get; set; }
        public string RISLookupManholePurpose6_Key { get; set; }
        public Nullable<double> GISOffsetPoint { get; set; }
        public string Comments { get; set; }
        public Nullable<double> XCoordinate { get; set; }
        public Nullable<double> YCoordinate { get; set; }
        public Nullable<double> ZCoordinate { get; set; }
        public System.Data.Spatial.DbGeometry GISLocation { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Flag { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
        public string RISLookupCondition_Key { get; set; }
        public Nullable<System.DateTime> ConditionDate { get; set; }
    
        public virtual RISLookupCondition RISLookupCondition { get; set; }
        public virtual RISLookupManholeMaterial RISLookupManholeMaterial { get; set; }
        public virtual RISLookupManholePlacement RISLookupManholePlacement { get; set; }
        public virtual RISLookupManholePurpose RISLookupManholePurpose { get; set; }
        public virtual RISLookupManholePurpose RISLookupManholePurpose1 { get; set; }
        public virtual RISLookupManholePurpose RISLookupManholePurpose2 { get; set; }
        public virtual RISLookupManholePurpose RISLookupManholePurpose3 { get; set; }
        public virtual RISLookupManholePurpose RISLookupManholePurpose4 { get; set; }
        public virtual RISLookupManholePurpose RISLookupManholePurpose5 { get; set; }
        public virtual Road Road { get; set; }
        public virtual ICollection<RISManHoleHistory> RISManHoleHistories { get; set; }
    }
}
