//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISMaintenanceScheduleHistory
    {
        public string RISMaintenanceScheduleHistory_Key { get; set; }
        public string Road_Key { get; set; }
        public string RISMaintenanceType_Key { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
        public string RISSeason_Key { get; set; }
        public Nullable<decimal> BeginMilepost { get; set; }
        public Nullable<decimal> EndMilepost { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISMaintenanceType RISMaintenanceType { get; set; }
        public virtual RISSeason RISSeason { get; set; }
        public virtual Road Road { get; set; }
    }
}
