//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISMUTCD
    {
        public RISMUTCD()
        {
            this.RISSigns = new HashSet<RISSign>();
        }
    
        public string RISMUTCD_Key { get; set; }
        public string MUTCD { get; set; }
        public string Legend { get; set; }
        public string NameDesc { get; set; }
        public string DescName { get; set; }
        public Nullable<double> SignHeight { get; set; }
        public Nullable<double> SignWidth { get; set; }
        public string ForegroundColor { get; set; }
        public string BackgroundColor { get; set; }
        public Nullable<double> ReplacementCost { get; set; }
        public string Flag { get; set; }
        public string Editable { get; set; }
        public byte[] SignImage { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
        public bool IsSystemData { get; set; }
    
        public virtual ICollection<RISSign> RISSigns { get; set; }
    }
}
