//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISMaintenanceDistrict
    {
        public RISMaintenanceDistrict()
        {
            this.Permits = new HashSet<Permit>();
            this.RISCulverts = new HashSet<RISCulvert>();
            this.RISJurisdictions = new HashSet<RISJurisdiction>();
            this.RISSigns = new HashSet<RISSign>();
        }
    
        public string RISMaintenanceDistrict_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NameDesc { get; set; }
        public string DescName { get; set; }
        public string Zone_Key { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<Permit> Permits { get; set; }
        public virtual ICollection<RISCulvert> RISCulverts { get; set; }
        public virtual ICollection<RISJurisdiction> RISJurisdictions { get; set; }
        public virtual Zone Zone { get; set; }
        public virtual ICollection<RISSign> RISSigns { get; set; }
    }
}
