//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISRoadSegment
    {
        public int RISRoadSegment_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal BeginMilepost { get; set; }
        public decimal EndMilepost { get; set; }
        public Nullable<decimal> TotalSegmentMiles { get; set; }
        public string RISLookupFederalFunctionalClass_Key { get; set; }
        public string RISCountyFunctionalClass_Key { get; set; }
        public string RISLookupSurface_Key { get; set; }
        public Nullable<decimal> SurfaceTypeWidth { get; set; }
        public string RISLookupJurisdiction_Key { get; set; }
        public string RISLookupCity_Key { get; set; }
        public string RISMaintenanceDistrict_Key { get; set; }
        public byte MPO { get; set; }
        public Nullable<double> Lanes { get; set; }
        public Nullable<double> LaneWidth { get; set; }
        public Nullable<double> LaneMiles { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Road Road { get; set; }
    }
}
