//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISRoadSegmentSetup
    {
        public int RISRoadSegmentSetup_Key { get; set; }
        public byte IncludeFunctionalClass { get; set; }
        public byte IncludeSurfaceType { get; set; }
        public byte IncludeJurisdiction { get; set; }
        public byte IncludeLane { get; set; }
    }
}
