//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISRRCross
    {
        public string RISRRCross_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal Milepost { get; set; }
        public string RISLookupRRCrossTrafficDevice_Key { get; set; }
        public string TrackOwner { get; set; }
        public string CrossingNumber { get; set; }
        public string RISLookupRRCrossVehicle_Key { get; set; }
        public Nullable<double> NumberOfTracks { get; set; }
        public Nullable<double> SkewAngle { get; set; }
        public string Comments { get; set; }
        public Nullable<double> XCoordinate { get; set; }
        public Nullable<double> YCoordinate { get; set; }
        public Nullable<double> ZCoordinate { get; set; }
        public System.Data.Spatial.DbGeometry GISLocation { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Flag { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISLookupRRCrossTrafficDevice RISLookupRRCrossTrafficDevice { get; set; }
        public virtual RISLookupRRCrossVehicle RISLookupRRCrossVehicle { get; set; }
        public virtual Road Road { get; set; }
    }
}
