//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISRightOfWay
    {
        public string RISRightOfWay_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal BeginMilepost { get; set; }
        public decimal EndMilepost { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> LeftWidth { get; set; }
        public Nullable<double> RightWidth { get; set; }
        public string FilingReference { get; set; }
        public string RISLookupOwnerShipRight_Key { get; set; }
        public string RISLookupOwnerShipLeft_Key { get; set; }
        public string Township { get; set; }
        public Nullable<decimal> TownshipPartial { get; set; }
        public string TownshipDirection { get; set; }
        public string Range { get; set; }
        public Nullable<decimal> RangePartial { get; set; }
        public string RangeDirection { get; set; }
        public string Section { get; set; }
        public string SectionQuarter { get; set; }
        public string SectionQuarterQuarter { get; set; }
        public string Anomaly { get; set; }
        public string MapSuffixType { get; set; }
        public string MapSuffixNumber { get; set; }
        public string TaxlotNumber { get; set; }
        public string RecordingDocumentNumber { get; set; }
        public string Comments { get; set; }
        public byte GASB34 { get; set; }
        public string Project_Key { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual RISLookupOwnerShipLeft RISLookupOwnerShipLeft { get; set; }
        public virtual RISLookupOwnerShipRight RISLookupOwnerShipRight { get; set; }
        public virtual Road Road { get; set; }
    }
}
