//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISSignHistoryAudit
    {
        public int RISSignHistoryAudit_Key { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionType { get; set; }
        public string UserName { get; set; }
        public string AuditComments { get; set; }
        public string RISSignHistory_Key { get; set; }
        public string RISSign_Key { get; set; }
        public string RISSignHistoryCause_Key { get; set; }
        public string RISSignHistoryAction_Key { get; set; }
        public string RISLookupCondition_Key { get; set; }
        public string RISLookupReflectivityCondition_Key { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public Nullable<System.DateTime> SignTime { get; set; }
        public string AssetNumber { get; set; }
        public string Employee { get; set; }
        public Nullable<short> LegendRetroReflectivity { get; set; }
        public Nullable<short> BackGroundRetroReflectivity { get; set; }
        public string Comments { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISLookupCondition RISLookupCondition { get; set; }
        public virtual RISLookupCondition RISLookupCondition1 { get; set; }
    }
}
