//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISSignAudit
    {
        public int RISSignAudit_Key { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionType { get; set; }
        public string UserName { get; set; }
        public string AuditComments { get; set; }
        public string RISSign_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal Milepost { get; set; }
        public byte Active { get; set; }
        public Nullable<double> SignId { get; set; }
        public string RISLookupSignPlacement_Key { get; set; }
        public string RISMutcd_Key { get; set; }
        public string RISMutcdLegend_Key { get; set; }
        public string CountySign { get; set; }
        public string Legend { get; set; }
        public Nullable<double> SignHeight { get; set; }
        public Nullable<double> SignWidth { get; set; }
        public string ForegroundColor { get; set; }
        public string BackgroundColor { get; set; }
        public Nullable<double> PostLength { get; set; }
        public Nullable<double> OffsetDistance { get; set; }
        public Nullable<double> HeightOnPost { get; set; }
        public Nullable<double> PositionOnPost { get; set; }
        public string RISLookupSignMaterial_Key { get; set; }
        public string RISLookupSignSurface_Key { get; set; }
        public string CountyPostID { get; set; }
        public Nullable<double> NumberOfPosts { get; set; }
        public string RISLookupSignPost_Key { get; set; }
        public string RISLookupDirection_Key { get; set; }
        public Nullable<System.DateTime> ConditionDate { get; set; }
        public string RISLookupCondition_Key { get; set; }
        public string RISLookupReflectivityCondition_Key { get; set; }
        public string RISLookupSignReflectivityGrade_Key { get; set; }
        public string RISMaintenanceDistrict_Key { get; set; }
        public Nullable<short> LegendRetroReflectivity { get; set; }
        public Nullable<short> BackGroundRetroReflectivity { get; set; }
        public string AssetNumber { get; set; }
        public string Comments { get; set; }
        public Nullable<double> XCoordinate { get; set; }
        public Nullable<double> YCoordinate { get; set; }
        public Nullable<double> ZCoordinate { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Road Road { get; set; }
    }
}
