//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISSignal
    {
        public string RISSignal_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal Milepost { get; set; }
        public string XRoadNumber { get; set; }
        public string XRoadName { get; set; }
        public string XRoadType { get; set; }
        public string XRoadDirection { get; set; }
        public Nullable<double> XRoadMilepost { get; set; }
        public string RISLookupSignalControl_Key { get; set; }
        public string RISLookupSignalActuate_Key { get; set; }
        public string RISLookupSignalMaterial_Key { get; set; }
        public string RISLookupSignalMount_Key { get; set; }
        public string RISLookupSignalConfiguration_Key { get; set; }
        public string RISLookupSignalDetectionType_Key { get; set; }
        public string RISLookupSignalPowerSource_Key { get; set; }
        public string RISLookupSignalPedestrianHeadType_Key { get; set; }
        public string RISLookupSignalInterConnect_Key { get; set; }
        public string RISLookupSignalRemoteConnectionType_Key { get; set; }
        public string RISLookupSignalPreemptionType_Key { get; set; }
        public Nullable<double> NumberVehicleSignalHead { get; set; }
        public Nullable<double> NumberPedSignalHead { get; set; }
        public Nullable<byte> Preemption { get; set; }
        public Nullable<System.DateTime> DateInspected { get; set; }
        public string AssetNumber { get; set; }
        public string Owner { get; set; }
        public string MaintenanceJurisdiction { get; set; }
        public string Comments { get; set; }
        public byte FlashingYellowArrow { get; set; }
        public Nullable<double> XCoordinate { get; set; }
        public Nullable<double> YCoordinate { get; set; }
        public Nullable<double> ZCoordinate { get; set; }
        public System.Data.Spatial.DbGeometry GISLocation { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Flag { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISLookupSignalActuate RISLookupSignalActuate { get; set; }
        public virtual RISLookupSignalConfiguration RISLookupSignalConfiguration { get; set; }
        public virtual RISLookupSignalControl RISLookupSignalControl { get; set; }
        public virtual RISLookupSignalDetectionType RISLookupSignalDetectionType { get; set; }
        public virtual RISLookupSignalInterConnect RISLookupSignalInterConnect { get; set; }
        public virtual RISLookupSignalMaterial RISLookupSignalMaterial { get; set; }
        public virtual RISLookupSignalMount RISLookupSignalMount { get; set; }
        public virtual RISLookupSignalPedestrianHeadType RISLookupSignalPedestrianHeadType { get; set; }
        public virtual RISLookupSignalPowerSource RISLookupSignalPowerSource { get; set; }
        public virtual RISLookupSignalPreemptionType RISLookupSignalPreemptionType { get; set; }
        public virtual RISLookupSignalRemoteConnectionType RISLookupSignalRemoteConnectionType { get; set; }
        public virtual Road Road { get; set; }
    }
}
