//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISStripMapHeader
    {
        public int RISStripMapHeader_Key { get; set; }
        public string Road_Key { get; set; }
        public string RISLocationReference_Key { get; set; }
        public string RoadNumber { get; set; }
        public string BeginDescription { get; set; }
        public string EndDescription { get; set; }
        public string CountyCode { get; set; }
        public string Jurisdiction { get; set; }
        public string RoadDirection { get; set; }
        public string Township { get; set; }
        public string Range { get; set; }
        public string Section { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISLocationReference RISLocationReference { get; set; }
        public virtual Road Road { get; set; }
    }
}
