//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISStripMapDetail
    {
        public int RISStripMapDetail_Key { get; set; }
        public string RISLocationReference_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal Milepost { get; set; }
        public string LeftText { get; set; }
        public string CenterText { get; set; }
        public string RightText { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Road Road { get; set; }
    }
}
