//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISSeason
    {
        public RISSeason()
        {
            this.RISMaintenanceScheduleHistories = new HashSet<RISMaintenanceScheduleHistory>();
        }
    
        public string RISSeason_Key { get; set; }
        public string Season { get; set; }
        public byte BeginDay { get; set; }
        public byte EndDay { get; set; }
        public byte BeginMonth { get; set; }
        public byte EndMonth { get; set; }
        public string NameDesc { get; set; }
    
        public virtual ICollection<RISMaintenanceScheduleHistory> RISMaintenanceScheduleHistories { get; set; }
    }
}
