//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISUniqueRoute
    {
        public string RISUniqueRoute_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal BeginMilepost { get; set; }
        public decimal EndMilepost { get; set; }
        public Nullable<byte> NationalForestHwy { get; set; }
        public Nullable<byte> ResourceRoad { get; set; }
        public Nullable<byte> ScenicRoad { get; set; }
        public Nullable<byte> School { get; set; }
        public Nullable<byte> Mail { get; set; }
        public Nullable<byte> PublicBus { get; set; }
        public Nullable<byte> DesignatedTruckRoute { get; set; }
        public Nullable<byte> SnowPlowRoute { get; set; }
        public Nullable<byte> IceControlRoute { get; set; }
        public Nullable<byte> EmergencyTransportationRoute { get; set; }
        public Nullable<byte> PermitRoute { get; set; }
        public string Comments { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Flag { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Road Road { get; set; }
    }
}
