//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISWheelChair
    {
        public string RISWheelChair_Key { get; set; }
        public string Road_Key { get; set; }
        public decimal Milepost { get; set; }
        public string RISLookupWheelChairPlacement_Key { get; set; }
        public Nullable<byte> IsADA { get; set; }
        public Nullable<byte> ConcreteLandingPad { get; set; }
        public Nullable<double> Vertical { get; set; }
        public Nullable<double> Horizontal { get; set; }
        public Nullable<double> FlatArea { get; set; }
        public Nullable<double> Wings { get; set; }
        public Nullable<byte> Texture { get; set; }
        public Nullable<byte> Color { get; set; }
        public Nullable<double> ApproachLip { get; set; }
        public Nullable<byte> RampProvided { get; set; }
        public string XRoadNumber { get; set; }
        public string XRoadName { get; set; }
        public string XRoadType { get; set; }
        public string XRoadDirection { get; set; }
        public string RISLookupCondition_Key { get; set; }
        public Nullable<System.DateTime> DateInspected { get; set; }
        public string Comments { get; set; }
        public Nullable<double> XCoordinate { get; set; }
        public Nullable<double> YCoordinate { get; set; }
        public Nullable<double> ZCoordinate { get; set; }
        public System.Data.Spatial.DbGeometry GISLocation { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Flag { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISLookupCondition RISLookupCondition { get; set; }
        public virtual RISLookupWheelChairPlacement RISLookupWheelChairPlacement { get; set; }
        public virtual Road Road { get; set; }
    }
}
