//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISWall
    {
        public string RISWall_Key { get; set; }
        public string Road_Key { get; set; }
        public string RISLookupWallPlacement_Key { get; set; }
        public string RISLookupWallType_Key { get; set; }
        public string RISLookupWallPosition_Key { get; set; }
        public string RISLookupWallCondition_Key { get; set; }
        public decimal BeginMilepost { get; set; }
        public decimal EndMilepost { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Offset { get; set; }
        public Nullable<double> MaximumHeight { get; set; }
        public Nullable<double> Area { get; set; }
        public byte Guardrail { get; set; }
        public byte Fence { get; set; }
        public Nullable<System.DateTime> DateInspected { get; set; }
        public string InspectionCycle { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public string ProjectNumber { get; set; }
        public string Comments { get; set; }
        public byte Active { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual RISLookupWallCondition RISLookupWallCondition { get; set; }
        public virtual RISLookupWallPlacement RISLookupWallPlacement { get; set; }
        public virtual RISLookupWallPosition RISLookupWallPosition { get; set; }
        public virtual RISLookupWallType RISLookupWallType { get; set; }
        public virtual Road Road { get; set; }
    }
}
