//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoadName
    {
        public RoadName()
        {
            this.Permits = new HashSet<Permit>();
            this.Permits1 = new HashSet<Permit>();
            this.TimeCards = new HashSet<TimeCard>();
            this.Transact_History = new HashSet<Transact_History>();
            this.Transacts = new HashSet<Transact>();
            this.VMSSprayReports = new HashSet<VMSSprayReport>();
            this.SRSRequests = new HashSet<SRSRequest>();
        }
    
        public string RoadName_Key { get; set; }
        public string Road_Key { get; set; }
        public string RoadName1 { get; set; }
        public decimal BeginMilepost { get; set; }
        public decimal EndMilepost { get; set; }
        public string RISLookupRoadNameRoadType_Key { get; set; }
        public string RISLookupRoadNameDirection_Key { get; set; }
        public string Comments { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string RoadNameTypeDirection { get; set; }
        public string FullRoadName { get; set; }
        public string NameDesc { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<Permit> Permits { get; set; }
        public virtual ICollection<Permit> Permits1 { get; set; }
        public virtual Road Road { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
        public virtual ICollection<Transact_History> Transact_History { get; set; }
        public virtual ICollection<Transact> Transacts { get; set; }
        public virtual ICollection<VMSSprayReport> VMSSprayReports { get; set; }
        public virtual ICollection<SRSRequest> SRSRequests { get; set; }
    }
}
