//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Road
    {
        public Road()
        {
            this.APSPayables = new HashSet<APSPayable>();
            this.CrewSheets = new HashSet<CrewSheet>();
            this.Projects = new HashSet<Project>();
            this.RISAccidents = new HashSet<RISAccident>();
            this.RISAdjDevelops = new HashSet<RISAdjDevelop>();
            this.RISAdoptARoads = new HashSet<RISAdoptARoad>();
            this.RISADTs = new HashSet<RISADT>();
            this.RISApproaches = new HashSet<RISApproach>();
            this.RISBikeFacilities = new HashSet<RISBikeFacility>();
            this.RISBridges = new HashSet<RISBridge>();
            this.RISCatchBasins = new HashSet<RISCatchBasin>();
            this.RISCuldesacs = new HashSet<RISCuldesac>();
            this.RISCulverts = new HashSet<RISCulvert>();
            this.RISCurbs = new HashSet<RISCurb>();
            this.RISDitches = new HashSet<RISDitch>();
            this.RISGates = new HashSet<RISGate>();
            this.RISGuardRails = new HashSet<RISGuardRail>();
            this.RISIlluminations = new HashSet<RISIllumination>();
            this.RISIntersections = new HashSet<RISIntersection>();
            this.RISJurisdictions = new HashSet<RISJurisdiction>();
            this.RISLanes = new HashSet<RISLane>();
            this.RISLevees = new HashSet<RISLevee>();
            this.RISLocationReferenceDatas = new HashSet<RISLocationReferenceData>();
            this.RISMaintenanceRoutes = new HashSet<RISMaintenanceRoute>();
            this.RISMaintenanceSchedules = new HashSet<RISMaintenanceSchedule>();
            this.RISMaintenanceScheduleHistories = new HashSet<RISMaintenanceScheduleHistory>();
            this.RISManHoles = new HashSet<RISManHole>();
            this.RISMapLocators = new HashSet<RISMapLocator>();
            this.RISMedians = new HashSet<RISMedian>();
            this.RISMonuments = new HashSet<RISMonument>();
            this.RISPavemarks = new HashSet<RISPavemark>();
            this.RISReferencePoints = new HashSet<RISReferencePoint>();
            this.RISRestrictedParkings = new HashSet<RISRestrictedParking>();
            this.RISRightOfWays = new HashSet<RISRightOfWay>();
            this.RISRoadClasses = new HashSet<RISRoadClass>();
            this.RISRoadClassAudits = new HashSet<RISRoadClassAudit>();
            this.RISRoadConstraints = new HashSet<RISRoadConstraint>();
            this.RISRoadSegments = new HashSet<RISRoadSegment>();
            this.RISRRCrosses = new HashSet<RISRRCross>();
            this.RISShoulders = new HashSet<RISShoulder>();
            this.RISSigns = new HashSet<RISSign>();
            this.RISSignals = new HashSet<RISSignal>();
            this.RISSignAudits = new HashSet<RISSignAudit>();
            this.RISSpeedZones = new HashSet<RISSpeedZone>();
            this.RISStreetAddresses = new HashSet<RISStreetAddress>();
            this.RISStreetAddresses1 = new HashSet<RISStreetAddress>();
            this.RISStripMapDetails = new HashSet<RISStripMapDetail>();
            this.RISStripMapHeaders = new HashSet<RISStripMapHeader>();
            this.RISSurfaceTypes = new HashSet<RISSurfaceType>();
            this.RISUniqueRoutes = new HashSet<RISUniqueRoute>();
            this.RISUtilities = new HashSet<RISUtility>();
            this.RISWalks = new HashSet<RISWalk>();
            this.RISWalls = new HashSet<RISWall>();
            this.RISWheelChairs = new HashSet<RISWheelChair>();
            this.RoadNames = new HashSet<RoadName>();
            this.VMSPURSReports = new HashSet<VMSPURSReport>();
            this.TimeCards = new HashSet<TimeCard>();
            this.Transacts = new HashSet<Transact>();
            this.Transact_History = new HashSet<Transact_History>();
            this.VMSSprayReports = new HashSet<VMSSprayReport>();
        }
    
        public string Road_Key { get; set; }
        public string RoadNumber { get; set; }
        public decimal BeginMilepost { get; set; }
        public decimal EndMilepost { get; set; }
        public string BeginDescription { get; set; }
        public string EndDescription { get; set; }
        public Nullable<decimal> RoadLength { get; set; }
        public string CommonRoad { get; set; }
        public string FullRoadNumber { get; set; }
        public string NameDesc { get; set; }
        public string DescName { get; set; }
        public string Comments { get; set; }
        public string Mgt_Unit_Key { get; set; }
        public string Program_Key { get; set; }
        public string Zone_Key { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string NotUsed1 { get; set; }
        public string NotUsed2 { get; set; }
        public string NotUsed3 { get; set; }
        public string NotUsed4 { get; set; }
        public string NotUsed5 { get; set; }
        public byte Active { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<APSPayable> APSPayables { get; set; }
        public virtual ICollection<CrewSheet> CrewSheets { get; set; }
        public virtual Mgt_Unit Mgt_Unit { get; set; }
        public virtual Program Program { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<RISAccident> RISAccidents { get; set; }
        public virtual ICollection<RISAdjDevelop> RISAdjDevelops { get; set; }
        public virtual ICollection<RISAdoptARoad> RISAdoptARoads { get; set; }
        public virtual ICollection<RISADT> RISADTs { get; set; }
        public virtual ICollection<RISApproach> RISApproaches { get; set; }
        public virtual ICollection<RISBikeFacility> RISBikeFacilities { get; set; }
        public virtual ICollection<RISBridge> RISBridges { get; set; }
        public virtual ICollection<RISCatchBasin> RISCatchBasins { get; set; }
        public virtual ICollection<RISCuldesac> RISCuldesacs { get; set; }
        public virtual ICollection<RISCulvert> RISCulverts { get; set; }
        public virtual ICollection<RISCurb> RISCurbs { get; set; }
        public virtual ICollection<RISDitch> RISDitches { get; set; }
        public virtual ICollection<RISGate> RISGates { get; set; }
        public virtual ICollection<RISGuardRail> RISGuardRails { get; set; }
        public virtual ICollection<RISIllumination> RISIlluminations { get; set; }
        public virtual ICollection<RISIntersection> RISIntersections { get; set; }
        public virtual ICollection<RISJurisdiction> RISJurisdictions { get; set; }
        public virtual ICollection<RISLane> RISLanes { get; set; }
        public virtual ICollection<RISLevee> RISLevees { get; set; }
        public virtual ICollection<RISLocationReferenceData> RISLocationReferenceDatas { get; set; }
        public virtual ICollection<RISMaintenanceRoute> RISMaintenanceRoutes { get; set; }
        public virtual ICollection<RISMaintenanceSchedule> RISMaintenanceSchedules { get; set; }
        public virtual ICollection<RISMaintenanceScheduleHistory> RISMaintenanceScheduleHistories { get; set; }
        public virtual ICollection<RISManHole> RISManHoles { get; set; }
        public virtual ICollection<RISMapLocator> RISMapLocators { get; set; }
        public virtual ICollection<RISMedian> RISMedians { get; set; }
        public virtual ICollection<RISMonument> RISMonuments { get; set; }
        public virtual ICollection<RISPavemark> RISPavemarks { get; set; }
        public virtual ICollection<RISReferencePoint> RISReferencePoints { get; set; }
        public virtual ICollection<RISRestrictedParking> RISRestrictedParkings { get; set; }
        public virtual ICollection<RISRightOfWay> RISRightOfWays { get; set; }
        public virtual ICollection<RISRoadClass> RISRoadClasses { get; set; }
        public virtual ICollection<RISRoadClassAudit> RISRoadClassAudits { get; set; }
        public virtual ICollection<RISRoadConstraint> RISRoadConstraints { get; set; }
        public virtual ICollection<RISRoadSegment> RISRoadSegments { get; set; }
        public virtual ICollection<RISRRCross> RISRRCrosses { get; set; }
        public virtual ICollection<RISShoulder> RISShoulders { get; set; }
        public virtual ICollection<RISSign> RISSigns { get; set; }
        public virtual ICollection<RISSignal> RISSignals { get; set; }
        public virtual ICollection<RISSignAudit> RISSignAudits { get; set; }
        public virtual ICollection<RISSpeedZone> RISSpeedZones { get; set; }
        public virtual ICollection<RISStreetAddress> RISStreetAddresses { get; set; }
        public virtual ICollection<RISStreetAddress> RISStreetAddresses1 { get; set; }
        public virtual ICollection<RISStripMapDetail> RISStripMapDetails { get; set; }
        public virtual ICollection<RISStripMapHeader> RISStripMapHeaders { get; set; }
        public virtual ICollection<RISSurfaceType> RISSurfaceTypes { get; set; }
        public virtual ICollection<RISUniqueRoute> RISUniqueRoutes { get; set; }
        public virtual ICollection<RISUtility> RISUtilities { get; set; }
        public virtual ICollection<RISWalk> RISWalks { get; set; }
        public virtual ICollection<RISWall> RISWalls { get; set; }
        public virtual ICollection<RISWheelChair> RISWheelChairs { get; set; }
        public virtual Zone Zone { get; set; }
        public virtual ICollection<RoadName> RoadNames { get; set; }
        public virtual ICollection<VMSPURSReport> VMSPURSReports { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
        public virtual ICollection<Transact> Transacts { get; set; }
        public virtual ICollection<Transact_History> Transact_History { get; set; }
        public virtual ICollection<VMSSprayReport> VMSSprayReports { get; set; }
    }
}
