//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPTCriteriaSavedDetail
    {
        public string RPTCriteriaSavedDetail_Key { get; set; }
        public string RPTCriteriaSaved_Key { get; set; }
        public string RPTCriteria_Key { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public string Operator1 { get; set; }
        public string Operator2 { get; set; }
        public string Group1 { get; set; }
        public string Group2 { get; set; }
        public short OrdinalPosition { get; set; }
        public string SecurityUser_Key { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
    
        public virtual RPTCriteria RPTCriteria { get; set; }
        public virtual RPTCriteriaSaved RPTCriteriaSaved { get; set; }
    }
}
