//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPTSortSaved
    {
        public string RPTSortSaved_Key { get; set; }
        public string RPTCriteriaSaved_Key { get; set; }
        public string RPTCriteria_Key { get; set; }
        public byte OrdinalPosition { get; set; }
        public byte SortAscending { get; set; }
        public string SecurityUser_Key { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    
        public virtual RPTCriteria RPTCriteria { get; set; }
        public virtual RPTCriteriaSaved RPTCriteriaSaved { get; set; }
    }
}
