//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleParent
    {
        public string RuleParent_Key { get; set; }
        public string SecurityObject_Key { get; set; }
        public string TableName { get; set; }
        public string RuleName { get; set; }
        public string RuleDescription { get; set; }
        public string ParentWhereClause { get; set; }
        public string ChildWhereClause { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string SecurityUser_Key { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
    }
}
