//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityUser
    {
        public SecurityUser()
        {
            this.CRWHideFields = new HashSet<CRWHideField>();
            this.CRWSaveReports = new HashSet<CRWSaveReport>();
            this.CRWSaveReports1 = new HashSet<CRWSaveReport>();
            this.CRWSaveReportUsers = new HashSet<CRWSaveReportUser>();
            this.DropDownDetails = new HashSet<DropDownDetail>();
            this.ODOTPermits = new HashSet<ODOTPermit>();
            this.Permits = new HashSet<Permit>();
            this.Permits1 = new HashSet<Permit>();
            this.Reminders = new HashSet<Reminder>();
            this.RISGateHistories = new HashSet<RISGateHistory>();
            this.RISGuardRailHistories = new HashSet<RISGuardRailHistory>();
            this.SecurityGroupUsers = new HashSet<SecurityGroupUser>();
            this.SERUtilityPermits = new HashSet<SERUtilityPermit>();
            this.SERUtilityPermits1 = new HashSet<SERUtilityPermit>();
            this.SRSUsers = new HashSet<SRSUser>();
            this.TimeCards = new HashSet<TimeCard>();
            this.Transacts = new HashSet<Transact>();
            this.Transact_History = new HashSet<Transact_History>();
            this.Transact_History1 = new HashSet<Transact_History>();
            this.Transacts1 = new HashSet<Transact>();
            this.Transacts2 = new HashSet<Transact>();
        }
    
        public string SecurityUser_Key { get; set; }
        public string LoginName { get; set; }
        public string UserName { get; set; }
        public string Employee_Key { get; set; }
        public string NameDesc { get; set; }
        public string Password { get; set; }
        public byte[] Signature { get; set; }
        public string NETPassword { get; set; }
        public string Email { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string Entered_By { get; set; }
        public bool IsSuperVisorKey { get; set; }
        public bool IsUserKey { get; set; }
    
        public virtual ICollection<CRWHideField> CRWHideFields { get; set; }
        public virtual ICollection<CRWSaveReport> CRWSaveReports { get; set; }
        public virtual ICollection<CRWSaveReport> CRWSaveReports1 { get; set; }
        public virtual ICollection<CRWSaveReportUser> CRWSaveReportUsers { get; set; }
        public virtual ICollection<DropDownDetail> DropDownDetails { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<ODOTPermit> ODOTPermits { get; set; }
        public virtual ICollection<Permit> Permits { get; set; }
        public virtual ICollection<Permit> Permits1 { get; set; }
        public virtual ICollection<Reminder> Reminders { get; set; }
        public virtual ICollection<RISGateHistory> RISGateHistories { get; set; }
        public virtual ICollection<RISGuardRailHistory> RISGuardRailHistories { get; set; }
        public virtual ICollection<SecurityGroupUser> SecurityGroupUsers { get; set; }
        public virtual ICollection<SERUtilityPermit> SERUtilityPermits { get; set; }
        public virtual ICollection<SERUtilityPermit> SERUtilityPermits1 { get; set; }
        public virtual ICollection<SRSUser> SRSUsers { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
        public virtual ICollection<Transact> Transacts { get; set; }
        public virtual ICollection<Transact_History> Transact_History { get; set; }
        public virtual ICollection<Transact_History> Transact_History1 { get; set; }
        public virtual ICollection<Transact> Transacts1 { get; set; }
        public virtual ICollection<Transact> Transacts2 { get; set; }
    }
}
