//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityGroupUser
    {
        public int SecurityGroupUser_Key { get; set; }
        public string SecurityGroup_Key { get; set; }
        public string SecurityUser_Key { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    
        public virtual SecurityGroup SecurityGroup { get; set; }
        public virtual SecurityUser SecurityUser { get; set; }
    }
}
