//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityGroupField
    {
        public int SecurityGroupField_Key { get; set; }
        public string SecurityGroup_Key { get; set; }
        public string FieldProp_Key { get; set; }
    
        public virtual SecurityGroup SecurityGroup { get; set; }
    }
}
