//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERUtilityPermit
    {
        public string SERUtilityPermit_Key { get; set; }
        public string SERLookupUtilityPermitType_Key { get; set; }
        public string PermitNumber { get; set; }
        public string RoadName_Key { get; set; }
        public decimal Milepost { get; set; }
        public decimal BeginMilepost { get; set; }
        public decimal EndMilepost { get; set; }
        public string SERLookupUtilityPermitStatus_Key { get; set; }
        public string SERLookupUtilityPermitSurface_Key { get; set; }
        public string SERLookupUtilityPermitPlacement_Key { get; set; }
        public string SERLookupUtilityPermitInstalledLocation_Key { get; set; }
        public string SERLookupUtilityPermitUtilityInstalled_Key { get; set; }
        public string SecurityUser2_Key { get; set; }
        public string IssuedByPosition { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string CuttingOfSurfacePermitted { get; set; }
        public string LocationDescription { get; set; }
        public string Applicant { get; set; }
        public string ApplicantPosition { get; set; }
        public string ApplicantCompany { get; set; }
        public string ApplicantAddress { get; set; }
        public string ApplicantCity { get; set; }
        public string ApplicantState { get; set; }
        public string ApplicantZip { get; set; }
        public string ApplicantCityStateZip { get; set; }
        public string ApplicantPhone { get; set; }
        public string ApplicantMobile { get; set; }
        public string ApplicantFax { get; set; }
        public string ApplicantEmail { get; set; }
        public string SubContractorCompanyName { get; set; }
        public string SubContractorContact { get; set; }
        public string SubContractorContactJobTitle { get; set; }
        public string SubContractorAddress { get; set; }
        public string SubContractorCity { get; set; }
        public string SubContractorState { get; set; }
        public string SubContractorZip { get; set; }
        public string SubContractorCityStateZip { get; set; }
        public string SubContractorPhone { get; set; }
        public string SubContractorMobile { get; set; }
        public string SubContractorFax { get; set; }
        public string SubContractorEmail { get; set; }
        public string SubContractorNumber { get; set; }
        public string Township { get; set; }
        public string Range { get; set; }
        public string Section { get; set; }
        public string WorkOrderNumber { get; set; }
        public string ScopeOfWork { get; set; }
        public Nullable<decimal> ROWWidth { get; set; }
        public Nullable<System.DateTime> ReadyForInspectionDate { get; set; }
        public string InspectedBy { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public string Comment { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual SecurityUser SecurityUser { get; set; }
        public virtual SecurityUser SecurityUser1 { get; set; }
        public virtual SERLookupUtilityPermitInstalledLocation SERLookupUtilityPermitInstalledLocation { get; set; }
        public virtual SERLookupUtilityPermitPlacement SERLookupUtilityPermitPlacement { get; set; }
        public virtual SERLookupUtilityPermitStatu SERLookupUtilityPermitStatu { get; set; }
        public virtual SERLookupUtilityPermitSurface SERLookupUtilityPermitSurface { get; set; }
        public virtual SERLookupUtilityPermitType SERLookupUtilityPermitType { get; set; }
        public virtual SERLookupUtilityPermitUtilityInstalled SERLookupUtilityPermitUtilityInstalled { get; set; }
    }
}
