//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRSRequest
    {
        public SRSRequest()
        {
            this.SRSRequestHistories = new HashSet<SRSRequestHistory>();
        }
    
        public string SRSRequest_Key { get; set; }
        public string SRSRequestCategory_Key { get; set; }
        public string RoadName_Key { get; set; }
        public Nullable<decimal> Milepost { get; set; }
        public string SRSUser_Key { get; set; }
        public string SRSServiceArea_Key { get; set; }
        public string SRSRequester_Key { get; set; }
        public string SRSContactMethod_Key { get; set; }
        public string SRSRequestType_Key { get; set; }
        public string SRSSection_Key { get; set; }
        public string SRSResponseMethod_Key { get; set; }
        public string SRSUser2_Key { get; set; }
        public string Project_Key { get; set; }
        public string RequestNumber { get; set; }
        public string NameDesc { get; set; }
        public string XStreet { get; set; }
        public string Address { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string Request { get; set; }
        public string PreviousSectionComment { get; set; }
        public byte FileArchive { get; set; }
        public string SRSPriority_Key { get; set; }
        public byte UtilityRequest { get; set; }
        public string PoleNumber { get; set; }
        public string UtilityMapNumber { get; set; }
        public string TaxLotNumber { get; set; }
        public byte Complete { get; set; }
        public string ViewStatus { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<System.DateTime> DateSectionAssigned { get; set; }
        public string LatDirection { get; set; }
        public string LatDegrees { get; set; }
        public string LatMinutes { get; set; }
        public string LatSeconds { get; set; }
        public string LongDirection { get; set; }
        public string LongDegrees { get; set; }
        public string LongMinutes { get; set; }
        public string LongSeconds { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string EntryScreen { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string SecurityUser_Key { get; set; }
        public int EmailAlertCount { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual RoadName RoadName { get; set; }
        public virtual SRSContactMethod SRSContactMethod { get; set; }
        public virtual SRSPriority SRSPriority { get; set; }
        public virtual SRSSection SRSSection { get; set; }
        public virtual SRSRequestCategory SRSRequestCategory { get; set; }
        public virtual SRSRequester SRSRequester { get; set; }
        public virtual SRSUser SRSUser { get; set; }
        public virtual SRSRequestType SRSRequestType { get; set; }
        public virtual SRSResponseMethod SRSResponseMethod { get; set; }
        public virtual SRSServiceArea SRSServiceArea { get; set; }
        public virtual ICollection<SRSRequestHistory> SRSRequestHistories { get; set; }
    }
}
