//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRSRequestAudit
    {
        public int SRSRequestAudit_Key { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionType { get; set; }
        public string UserName { get; set; }
        public string AuditComments { get; set; }
        public string SRSRequest_Key { get; set; }
        public string SRSRequestCategory_Key { get; set; }
        public string RoadName_Key { get; set; }
        public Nullable<decimal> Milepost { get; set; }
        public string SRSUser_Key { get; set; }
        public string SRSUser2_Key { get; set; }
        public string SRSServiceArea_Key { get; set; }
        public string SRSRequester_Key { get; set; }
        public string SRSContactMethod_Key { get; set; }
        public string SRSRequestType_Key { get; set; }
        public string SRSSection_Key { get; set; }
        public string SRSResponseMethod_Key { get; set; }
        public string Project_Key { get; set; }
        public string RequestNumber { get; set; }
        public string XStreet { get; set; }
        public string Address { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string Request { get; set; }
        public byte FileArchive { get; set; }
        public string SRSPriority_Key { get; set; }
        public byte UtilityRequest { get; set; }
        public string PoleNumber { get; set; }
        public string UtilityMapNumber { get; set; }
        public string TaxLotNumber { get; set; }
        public byte Complete { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<System.DateTime> DateSectionAssigned { get; set; }
        public string Viewstatus { get; set; }
        public string LatDirection { get; set; }
        public string LatDegrees { get; set; }
        public string LatMinutes { get; set; }
        public string LatSeconds { get; set; }
        public string LongDirection { get; set; }
        public string LongDegrees { get; set; }
        public string LongMinutes { get; set; }
        public string LongSeconds { get; set; }
        public string EntryScreen { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual SRSUser SRSUser { get; set; }
    }
}
