//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRSUser
    {
        public SRSUser()
        {
            this.SRSRequests = new HashSet<SRSRequest>();
            this.SRSRequestAudits = new HashSet<SRSRequestAudit>();
            this.SRSRequestHistories = new HashSet<SRSRequestHistory>();
            this.SRSSections = new HashSet<SRSSection>();
            this.SRSSectionDetails = new HashSet<SRSSectionDetail>();
        }
    
        public string SRSUser_Key { get; set; }
        public string SecurityUser2_Key { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NameDesc { get; set; }
        public string DescName { get; set; }
        public string Email { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual SecurityUser SecurityUser { get; set; }
        public virtual ICollection<SRSRequest> SRSRequests { get; set; }
        public virtual ICollection<SRSRequestAudit> SRSRequestAudits { get; set; }
        public virtual ICollection<SRSRequestHistory> SRSRequestHistories { get; set; }
        public virtual ICollection<SRSSection> SRSSections { get; set; }
        public virtual ICollection<SRSSectionDetail> SRSSectionDetails { get; set; }
    }
}
