//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public string States_Key { get; set; }
        public string State_Num { get; set; }
        public string State_Name { get; set; }
        public string NameDesc { get; set; }
    }
}
