//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWSInspectionHistory
    {
        public SWSInspectionHistory()
        {
            this.SWSInspectionHistoryUnits = new HashSet<SWSInspectionHistoryUnit>();
        }
    
        public string SWSInspectionHistory_Key { get; set; }
        public string SWSManagementSection_Key { get; set; }
        public Nullable<System.DateTime> InspectionBeginDate { get; set; }
        public Nullable<System.DateTime> InspectionEndDate { get; set; }
        public Nullable<int> InspectionRating { get; set; }
        public Nullable<int> ExtrapolatedAlligatorCrackingHigh { get; set; }
        public Nullable<int> ExtrapolatedAlligatorCrackingMedium { get; set; }
        public Nullable<int> ExtrapolatedAlligatorCrackingLow { get; set; }
        public Nullable<int> ExtrapolatedLongitudinalCrackingHigh { get; set; }
        public Nullable<int> ExtrapolatedLongitudinalCrackingMedium { get; set; }
        public Nullable<int> ExtrapolatedLongitudinalCrackingLow { get; set; }
        public Nullable<int> ExtrapolatedTransverseCrackingHigh { get; set; }
        public Nullable<int> ExtrapolatedTransverseCrackingMedium { get; set; }
        public Nullable<int> ExtrapolatedTransverseCrackingLow { get; set; }
        public Nullable<int> ExtrapolatedRavelingHigh { get; set; }
        public Nullable<int> ExtrapolatedRavelingMedium { get; set; }
        public Nullable<int> ExtrapolatedRavelingLow { get; set; }
        public Nullable<int> ExtrapolatedPatchingHigh { get; set; }
        public Nullable<int> ExtrapolatedPatchingMedium { get; set; }
        public Nullable<int> ExtrapolatedPatchingLow { get; set; }
        public Nullable<byte> MigratedFromStreetSaver { get; set; }
        public string SWSLookupRoadRating_Key { get; set; }
        public Nullable<byte> RoadRatingCalculatedFromInspectionRating { get; set; }
        public Nullable<byte> InspectionRatingCalculatedFromRoadRating { get; set; }
        public string SWSLookupRatingType_Key { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual SWSLookupRatingType SWSLookupRatingType { get; set; }
        public virtual SWSLookupRoadRating SWSLookupRoadRating { get; set; }
        public virtual SWSManagementSection SWSManagementSection { get; set; }
        public virtual ICollection<SWSInspectionHistoryUnit> SWSInspectionHistoryUnits { get; set; }
    }
}
