//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWSInspectionHistoryUnit
    {
        public SWSInspectionHistoryUnit()
        {
            this.SWSInspectionHistoryUnitDetails = new HashSet<SWSInspectionHistoryUnitDetail>();
        }
    
        public string SWSInspectionHistoryUnit_Key { get; set; }
        public string SWSInspectionHistory_Key { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<decimal> BeginMilepost { get; set; }
        public Nullable<decimal> EndMilepost { get; set; }
        public int InspectionLengthFeet { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual SWSInspectionHistory SWSInspectionHistory { get; set; }
        public virtual ICollection<SWSInspectionHistoryUnitDetail> SWSInspectionHistoryUnitDetails { get; set; }
    }
}
