//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWSLookupRatingType
    {
        public SWSLookupRatingType()
        {
            this.SWSInspectionHistories = new HashSet<SWSInspectionHistory>();
            this.SWSMaintenanceHistories = new HashSet<SWSMaintenanceHistory>();
            this.SWSManagementSections = new HashSet<SWSManagementSection>();
            this.SWSManagementSectionAudits = new HashSet<SWSManagementSectionAudit>();
            this.SWSRoadRatingHistories = new HashSet<SWSRoadRatingHistory>();
        }
    
        public string SWSLookupRatingType_Key { get; set; }
        public string Name { get; set; }
        public bool IsSystemData { get; set; }
    
        public virtual ICollection<SWSInspectionHistory> SWSInspectionHistories { get; set; }
        public virtual ICollection<SWSMaintenanceHistory> SWSMaintenanceHistories { get; set; }
        public virtual ICollection<SWSManagementSection> SWSManagementSections { get; set; }
        public virtual ICollection<SWSManagementSectionAudit> SWSManagementSectionAudits { get; set; }
        public virtual ICollection<SWSRoadRatingHistory> SWSRoadRatingHistories { get; set; }
    }
}
