//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWSLayerMaterial
    {
        public SWSLayerMaterial()
        {
            this.SWSLayerStructures = new HashSet<SWSLayerStructure>();
            this.SWSLayerTemplateDetails = new HashSet<SWSLayerTemplateDetail>();
            this.SWSMaintenanceTypeMaterials = new HashSet<SWSMaintenanceTypeMaterial>();
        }
    
        public string SWSLayerMaterial_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NameDesc { get; set; }
        public string DescName { get; set; }
        public decimal StructuralNumberPerInch { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<SWSLayerStructure> SWSLayerStructures { get; set; }
        public virtual ICollection<SWSLayerTemplateDetail> SWSLayerTemplateDetails { get; set; }
        public virtual ICollection<SWSMaintenanceTypeMaterial> SWSMaintenanceTypeMaterials { get; set; }
    }
}
