//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWSMaintenanceTypeMaterial
    {
        public string SWSMaintenanceTypeMaterial_Key { get; set; }
        public string SWSMaintenanceType_Key { get; set; }
        public byte Layer { get; set; }
        public string SWSLayerMaterial_Key { get; set; }
        public decimal Thickness { get; set; }
        public decimal StructuralNumberPerInch { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual SWSLayerMaterial SWSLayerMaterial { get; set; }
        public virtual SWSMaintenanceType SWSMaintenanceType { get; set; }
    }
}
