//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWSMaintenanceEntry
    {
        public string SWSMaintenanceEntry_Key { get; set; }
        public string SWSManagementSection_Key { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public string SWSMaintenanceType_Key { get; set; }
        public string CurrentSWSLookupRoadRating_Key { get; set; }
        public string SWSLookupRoadRating_Key { get; set; }
        public Nullable<int> CurrentInspectionRating { get; set; }
        public Nullable<int> IncreasePoints { get; set; }
        public Nullable<decimal> MaintenanceCost { get; set; }
        public string Comment { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual SWSLookupRoadRating SWSLookupRoadRating { get; set; }
        public virtual SWSLookupRoadRating SWSLookupRoadRating1 { get; set; }
        public virtual SWSMaintenanceType SWSMaintenanceType { get; set; }
        public virtual SWSManagementSection SWSManagementSection { get; set; }
    }
}
