//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWSMaintenanceType
    {
        public SWSMaintenanceType()
        {
            this.SWSMaintenanceEntries = new HashSet<SWSMaintenanceEntry>();
            this.SWSMaintenanceHistories = new HashSet<SWSMaintenanceHistory>();
            this.SWSMaintenanceTypeMaterials = new HashSet<SWSMaintenanceTypeMaterial>();
            this.SWSManagementSections = new HashSet<SWSManagementSection>();
            this.SWSManagementSectionAudits = new HashSet<SWSManagementSectionAudit>();
        }
    
        public string SWSMaintenanceType_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NameDesc { get; set; }
        public string DescName { get; set; }
        public Nullable<int> ArterialIncreasePoints { get; set; }
        public Nullable<int> CollectorIncreasePoints { get; set; }
        public Nullable<int> ResidentialLocalIncreasePoints { get; set; }
        public Nullable<int> OtherIncreasePoints { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<SWSMaintenanceEntry> SWSMaintenanceEntries { get; set; }
        public virtual ICollection<SWSMaintenanceHistory> SWSMaintenanceHistories { get; set; }
        public virtual ICollection<SWSMaintenanceTypeMaterial> SWSMaintenanceTypeMaterials { get; set; }
        public virtual ICollection<SWSManagementSection> SWSManagementSections { get; set; }
        public virtual ICollection<SWSManagementSectionAudit> SWSManagementSectionAudits { get; set; }
    }
}
