//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWSRoadRatingHistory
    {
        public string SWSRoadRatingHistory_Key { get; set; }
        public string SWSManagementSection_Key { get; set; }
        public Nullable<System.DateTime> RoadRatingDate { get; set; }
        public string SWSLookupRoadRating_Key { get; set; }
        public string SWSLookupRatingType_Key { get; set; }
        public Nullable<int> InspectionRating { get; set; }
        public Nullable<byte> RoadRatingCalculatedFromInspectionRating { get; set; }
        public Nullable<byte> InspectionRatingCalculatedFromRoadRating { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual SWSLookupRatingType SWSLookupRatingType { get; set; }
        public virtual SWSLookupRoadRating SWSLookupRoadRating { get; set; }
        public virtual SWSManagementSection SWSManagementSection { get; set; }
    }
}
