//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWSSurfaceDistressRating
    {
        public int SWSSurfaceDistressRating_Key { get; set; }
        public string SWSSurfaceDistress_Key { get; set; }
        public int DistressPercentageGroup { get; set; }
        public string DistressSeverity { get; set; }
        public int Rate { get; set; }
    
        public virtual SWSSurfaceDistress SWSSurfaceDistress { get; set; }
    }
}
