//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWSSurfaceRating
    {
        public int SWSSurfaceRating_Key { get; set; }
        public string AlligatorCrackingSeverity { get; set; }
        public int AlligatorCrackingPercentageGroup { get; set; }
        public int OtherDistressPercentageGroup { get; set; }
        public string PercentageGroupSeverity { get; set; }
        public int LCRate { get; set; }
        public int TCRate { get; set; }
        public int RavelRate { get; set; }
        public int PatchRate { get; set; }
    }
}
