//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeCard
    {
        public string Timecard_Key { get; set; }
        public string Employee_Key { get; set; }
        public System.DateTime Task_Date { get; set; }
        public string Fiscal_Key { get; set; }
        public string Crew_Num { get; set; }
        public string Activity_Key { get; set; }
        public Nullable<decimal> Production { get; set; }
        public Nullable<decimal> Labor_Quantity { get; set; }
        public string Pay_Type_Key { get; set; }
        public string Premium_Key { get; set; }
        public Nullable<decimal> Override_Labor_Rate { get; set; }
        public Nullable<decimal> Equipment_Quantity { get; set; }
        public string Equipment_Key { get; set; }
        public Nullable<decimal> Equipment_Unit_Cost { get; set; }
        public Nullable<decimal> EquipmentMiles { get; set; }
        public Nullable<decimal> EquipmentHours { get; set; }
        public Nullable<decimal> Material_Quantity { get; set; }
        public string UOM_Key { get; set; }
        public string Material_Description { get; set; }
        public Nullable<decimal> Material_Unit_Cost { get; set; }
        public string Inventory_Location_Key { get; set; }
        public Nullable<decimal> OutSideService_Quantity { get; set; }
        public string ResourceClass_Key { get; set; }
        public string OutSideServiceDescription { get; set; }
        public Nullable<decimal> OutSideServiceCost { get; set; }
        public string Mgt_Unit_Key { get; set; }
        public string Program_Key { get; set; }
        public string Zone_Key { get; set; }
        public string Project_Key { get; set; }
        public string ProjectSub_Key { get; set; }
        public string RBF_Key { get; set; }
        public string Road_Key { get; set; }
        public string RoadName_Key { get; set; }
        public Nullable<decimal> Beg_Point { get; set; }
        public Nullable<decimal> End_Point { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public string Reason_Key { get; set; }
        public string SRSRequestNumber { get; set; }
        public string Comments { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string Error_Message { get; set; }
        public bool Posted { get; set; }
        public byte FuelImport { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
        public string CreatedBySecurityUser_Key { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Fiscal Fiscal { get; set; }
        public virtual Inventory_Location Inventory_Location { get; set; }
        public virtual Mgt_Unit Mgt_Unit { get; set; }
        public virtual Pay_Type Pay_Type { get; set; }
        public virtual Premium Premium { get; set; }
        public virtual Program Program { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectSub ProjectSub { get; set; }
        public virtual RBF RBF { get; set; }
        public virtual Reason Reason { get; set; }
        public virtual ResourceClass ResourceClass { get; set; }
        public virtual Road Road { get; set; }
        public virtual RoadName RoadName { get; set; }
        public virtual SecurityUser SecurityUser { get; set; }
        public virtual UOM UOM { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
