//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UOM
    {
        public UOM()
        {
            this.Activities = new HashSet<Activity>();
            this.APSPayables = new HashSet<APSPayable>();
            this.ARSInvoiceApprovals = new HashSet<ARSInvoiceApproval>();
            this.ARSInvoiceDetails = new HashSet<ARSInvoiceDetail>();
            this.EMSParts = new HashSet<EMSPart>();
            this.Inventories = new HashSet<Inventory>();
            this.Permits = new HashSet<Permit>();
            this.ResourceClasses = new HashSet<ResourceClass>();
            this.TimeCards = new HashSet<TimeCard>();
            this.Transacts = new HashSet<Transact>();
            this.Transact_History = new HashSet<Transact_History>();
        }
    
        public string UOM_Key { get; set; }
        public string English_Name { get; set; }
        public string Metric_Name { get; set; }
        public string English_Conversion_Factor { get; set; }
        public string Metric_Conversion_Factor { get; set; }
        public string NameDesc { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<APSPayable> APSPayables { get; set; }
        public virtual ICollection<ARSInvoiceApproval> ARSInvoiceApprovals { get; set; }
        public virtual ICollection<ARSInvoiceDetail> ARSInvoiceDetails { get; set; }
        public virtual ICollection<EMSPart> EMSParts { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<Permit> Permits { get; set; }
        public virtual ICollection<ResourceClass> ResourceClasses { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
        public virtual ICollection<Transact> Transacts { get; set; }
        public virtual ICollection<Transact_History> Transact_History { get; set; }
    }
}
