//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UseLocationGP
    {
        public string UseLocationGPS_Key { get; set; }
        public string UseLocation_Key { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public int ListOrder { get; set; }
    
        public virtual UseLocation UseLocation { get; set; }
    }
}
