//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UseLocation
    {
        public UseLocation()
        {
            this.UseLocationGPS = new HashSet<UseLocationGP>();
        }
    
        public string UseLocation_Key { get; set; }
        public string Foreign_Key { get; set; }
        public byte UseLocationType { get; set; }
        public string NickName { get; set; }
        public byte IsPrivate { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string ZipCode4 { get; set; }
        public byte ZipOnly { get; set; }
        public string GPSName { get; set; }
        public string TownshipStart { get; set; }
        public string RangeStart { get; set; }
        public string SectionStart { get; set; }
        public string TownshipEnd { get; set; }
        public string RangeEnd { get; set; }
        public string SectionEnd { get; set; }
        public string TRSName { get; set; }
        public string SecurityUser_Key { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    
        public virtual ICollection<UseLocationGP> UseLocationGPS { get; set; }
    }
}
