//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDefinedField
    {
        public string UserDefinedField_Key { get; set; }
        public string Form_Key { get; set; }
        public string SecurityObject_Key { get; set; }
        public string User1 { get; set; }
        public string User1Type { get; set; }
        public string User1LookupValues_Key { get; set; }
        public string User2 { get; set; }
        public string User2Type { get; set; }
        public string User2LookupValues_Key { get; set; }
        public string User3 { get; set; }
        public string User3Type { get; set; }
        public string User3LookupValues_Key { get; set; }
        public string User4 { get; set; }
        public string User4Type { get; set; }
        public string User4LookupValues_Key { get; set; }
        public string User5 { get; set; }
        public string User5Type { get; set; }
        public string User5LookupValues_Key { get; set; }
        public string User6 { get; set; }
        public string User6Type { get; set; }
        public string User6LookupValues_Key { get; set; }
        public string User7 { get; set; }
        public string User7Type { get; set; }
        public string User7LookupValues_Key { get; set; }
        public string User8 { get; set; }
        public string User8Type { get; set; }
        public string User8LookupValues_Key { get; set; }
        public string User9 { get; set; }
        public string User9Type { get; set; }
        public string User9LookupValues_Key { get; set; }
        public string User10 { get; set; }
        public string User10Type { get; set; }
        public string User10LookupValues_key { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual LookupValue LookupValue { get; set; }
        public virtual LookupValue LookupValue1 { get; set; }
        public virtual LookupValue LookupValue2 { get; set; }
        public virtual LookupValue LookupValue3 { get; set; }
        public virtual LookupValue LookupValue4 { get; set; }
    }
}
