//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Sort_Join
    {
        public int USysUser_Sort_Join_Key { get; set; }
        public string SecurityUser_Key { get; set; }
        public string Sort_Key { get; set; }
        public Nullable<int> Ordinal_Position { get; set; }
        public bool Ascending_Order { get; set; }
        public bool IsSelected { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    }
}
