//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Defined_Tables
    {
        public int User_Defined_Tables_Key { get; set; }
        public string Table_Name { get; set; }
        public Nullable<System.DateTime> Datestamp { get; set; }
    }
}
