//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSAgentPurpose
    {
        public VMSAgentPurpose()
        {
            this.VMSPURSReportAgents = new HashSet<VMSPURSReportAgent>();
            this.VMSSprayReportAgents = new HashSet<VMSSprayReportAgent>();
        }
    
        public string VMSAgentPurpose_Key { get; set; }
        public string Name { get; set; }
        public byte Agriculture { get; set; }
        public byte Aquatic { get; set; }
        public byte Forestry { get; set; }
        public byte Other { get; set; }
        public byte Public_Health_Regulatory_Pests { get; set; }
        public byte Research { get; set; }
        public byte Right_of_Way { get; set; }
        public byte Urban_General_Indoor { get; set; }
        public byte Urban_General_Outdoor { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<VMSPURSReportAgent> VMSPURSReportAgents { get; set; }
        public virtual ICollection<VMSSprayReportAgent> VMSSprayReportAgents { get; set; }
    }
}
