//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSAgentProduct
    {
        public VMSAgentProduct()
        {
            this.VMSPURSReportAgents = new HashSet<VMSPURSReportAgent>();
            this.VMSSprayReportAgents = new HashSet<VMSSprayReportAgent>();
        }
    
        public string VMSAgentProducts_Key { get; set; }
        public string VMSAgent_Key { get; set; }
        public string ProductName { get; set; }
        public string AgentMixture { get; set; }
        public string Manufacturer { get; set; }
        public string Inventory_Location_Key { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Inventory_Location Inventory_Location { get; set; }
        public virtual VMSAgent VMSAgent { get; set; }
        public virtual ICollection<VMSPURSReportAgent> VMSPURSReportAgents { get; set; }
        public virtual ICollection<VMSSprayReportAgent> VMSSprayReportAgents { get; set; }
    }
}
