//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSAgent
    {
        public VMSAgent()
        {
            this.VMSAgentProducts = new HashSet<VMSAgentProduct>();
        }
    
        public string VMSAgent_Key { get; set; }
        public string ProductName { get; set; }
        public string EPANumber { get; set; }
        public string OtherProductNumber { get; set; }
        public string ProductFormulation { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<VMSAgentProduct> VMSAgentProducts { get; set; }
    }
}
