//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSConfig
    {
        public string VMSConfig_Key { get; set; }
        public byte PostTarget { get; set; }
        public string Activity_Key { get; set; }
        public string Project_Key { get; set; }
        public string Mgt_Unit_Key { get; set; }
        public string Program_Key { get; set; }
        public string Zone_Key { get; set; }
        public string VMSWaterShed_Key { get; set; }
        public byte UseEquipment { get; set; }
        public byte UseEmployee { get; set; }
        public byte UseMaterial { get; set; }
        public byte InsertEmployee { get; set; }
        public byte DisablePostedEdit { get; set; }
        public byte ValidateForAR { get; set; }
        public string PURSIDNumber { get; set; }
        public string PURSPassword { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Mgt_Unit Mgt_Unit { get; set; }
        public virtual Program Program { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
