//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSManagement
    {
        public VMSManagement()
        {
            this.VMSRevisits = new HashSet<VMSRevisit>();
        }
    
        public string VMSManagement_Key { get; set; }
        public string VMSVegetation_Key { get; set; }
        public string VMSPermitApp_Key { get; set; }
        public string VMSManagementType_Key { get; set; }
        public string ManagementNumber { get; set; }
        public Nullable<System.DateTime> ManagementDate { get; set; }
        public string Progress { get; set; }
        public string VMSSprayReport_Key { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual VMSVegetation VMSVegetation { get; set; }
        public virtual VMSManagementType VMSManagementType { get; set; }
        public virtual VMSPermitApp VMSPermitApp { get; set; }
        public virtual VMSSprayReport VMSSprayReport { get; set; }
        public virtual ICollection<VMSRevisit> VMSRevisits { get; set; }
    }
}
