//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSPlacement
    {
        public VMSPlacement()
        {
            this.VMSPermitApps = new HashSet<VMSPermitApp>();
            this.VMSVegetations = new HashSet<VMSVegetation>();
        }
    
        public string VMSPlacement_Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<VMSPermitApp> VMSPermitApps { get; set; }
        public virtual ICollection<VMSVegetation> VMSVegetations { get; set; }
    }
}
