//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSPermitApp
    {
        public VMSPermitApp()
        {
            this.VMSManagements = new HashSet<VMSManagement>();
            this.VMSUseLocations = new HashSet<VMSUseLocation>();
        }
    
        public string VMSPermitApp_Key { get; set; }
        public string PermitNumber { get; set; }
        public string VMSPermitType_Key { get; set; }
        public string VMSSprayStatus_Key { get; set; }
        public string Direction_Key { get; set; }
        public string IssuedBy { get; set; }
        public double Length { get; set; }
        public string VMSPlacement_Key { get; set; }
        public string Road_Key { get; set; }
        public Nullable<decimal> BegMP { get; set; }
        public Nullable<decimal> EndMP { get; set; }
        public Nullable<double> OffsetDistance { get; set; }
        public string CrossRoad_Key { get; set; }
        public string TaxlotNumber { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public byte NeverExpires { get; set; }
        public byte Organic { get; set; }
        public byte BusStop { get; set; }
        public byte CornerLot { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerLastName { get; set; }
        public string OwnerInitial { get; set; }
        public string OwnerAddress1 { get; set; }
        public string OwnerAddress2 { get; set; }
        public string OwnerPhone { get; set; }
        public string OwnerCity { get; set; }
        public string OwnerState { get; set; }
        public string OwnerZip { get; set; }
        public string SiteFirstName { get; set; }
        public string SiteLastName { get; set; }
        public string SiteInitial { get; set; }
        public string SiteAddress1 { get; set; }
        public string SiteAddress2 { get; set; }
        public string SiteHomePhone { get; set; }
        public string SiteWorkPhone { get; set; }
        public string SiteCity { get; set; }
        public string SiteState { get; set; }
        public string SiteZip { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<VMSManagement> VMSManagements { get; set; }
        public virtual VMSSprayStatu VMSSprayStatu { get; set; }
        public virtual VMSPlacement VMSPlacement { get; set; }
        public virtual VMSPermitType VMSPermitType { get; set; }
        public virtual ICollection<VMSUseLocation> VMSUseLocations { get; set; }
    }
}
