//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSPURSSpecificSite
    {
        public VMSPURSSpecificSite()
        {
            this.VMSPURSReports = new HashSet<VMSPURSReport>();
            this.VMSSpecificSites = new HashSet<VMSSpecificSite>();
        }
    
        public string VMSPURSSpecificSite_Key { get; set; }
        public string VMSPURSSiteCategory_Key { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<VMSPURSReport> VMSPURSReports { get; set; }
        public virtual VMSPURSSiteCategory VMSPURSSiteCategory { get; set; }
        public virtual ICollection<VMSSpecificSite> VMSSpecificSites { get; set; }
    }
}
