//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSPURSReport
    {
        public VMSPURSReport()
        {
            this.VMSPURSReportAgents = new HashSet<VMSPURSReportAgent>();
        }
    
        public string VMSPURSReport_Key { get; set; }
        public string ReportNumber { get; set; }
        public string VMSWaterShed_Key { get; set; }
        public Nullable<System.DateTime> SprayDate { get; set; }
        public string VMSPURSSiteCategory_Key { get; set; }
        public string VMSPURSSpecificSite_Key { get; set; }
        public string Zipcode { get; set; }
        public string Activity_Key { get; set; }
        public string Project_Key { get; set; }
        public string ProjectSub_Key { get; set; }
        public string Road_Key { get; set; }
        public string Mgt_Unit_Key { get; set; }
        public string Program_Key { get; set; }
        public string Zone_Key { get; set; }
        public byte Active { get; set; }
        public byte PURSPosted { get; set; }
        public byte CASPosted { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Mgt_Unit Mgt_Unit { get; set; }
        public virtual Program Program { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectSub ProjectSub { get; set; }
        public virtual Road Road { get; set; }
        public virtual VMSPURSSiteCategory VMSPURSSiteCategory { get; set; }
        public virtual VMSPURSSpecificSite VMSPURSSpecificSite { get; set; }
        public virtual VMSWaterShed VMSWaterShed { get; set; }
        public virtual Zone Zone { get; set; }
        public virtual ICollection<VMSPURSReportAgent> VMSPURSReportAgents { get; set; }
    }
}
