//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSSprayReport
    {
        public VMSSprayReport()
        {
            this.VMSManagements = new HashSet<VMSManagement>();
            this.VMSSprayReportAgents = new HashSet<VMSSprayReportAgent>();
            this.VMSSprayReportEmployees = new HashSet<VMSSprayReportEmployee>();
            this.VMSSprayReportEquipments = new HashSet<VMSSprayReportEquipment>();
            this.VMSSprayReportSurfactants = new HashSet<VMSSprayReportSurfactant>();
            this.VMSUseLocations = new HashSet<VMSUseLocation>();
        }
    
        public string VMSSprayReport_Key { get; set; }
        public string ReportNumber { get; set; }
        public string Activity_Key { get; set; }
        public string Mgt_Unit_Key { get; set; }
        public string Program_Key { get; set; }
        public string Zone_Key { get; set; }
        public string Project_Key { get; set; }
        public string ProjectSub_Key { get; set; }
        public string Road_Key { get; set; }
        public string RoadName_Key { get; set; }
        public string VMSWaterShed_Key { get; set; }
        public Nullable<decimal> BegMP { get; set; }
        public Nullable<decimal> EndMP { get; set; }
        public Nullable<System.DateTime> SprayDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string PUPNumber { get; set; }
        public string VMSSiteCategory_Key { get; set; }
        public string VMSSpecificSite_Key { get; set; }
        public string OtherSpecificSite { get; set; }
        public double AreaSprayed { get; set; }
        public string VMSAreaUOM_Key { get; set; }
        public string VMSWeather_Key { get; set; }
        public string VMSWindDirection_Key { get; set; }
        public string WindSpeed { get; set; }
        public Nullable<double> Temperature { get; set; }
        public string VMSControlType_Key { get; set; }
        public string ZipCode { get; set; }
        public string Customer_Key { get; set; }
        public string Vendor_Key { get; set; }
        public byte Active { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public byte CASPosted { get; set; }
        public byte PURSPosted { get; set; }
        public Nullable<int> AttachedDocuments { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Mgt_Unit Mgt_Unit { get; set; }
        public virtual Program Program { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectSub ProjectSub { get; set; }
        public virtual Road Road { get; set; }
        public virtual RoadName RoadName { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual VMSControlType VMSControlType { get; set; }
        public virtual ICollection<VMSManagement> VMSManagements { get; set; }
        public virtual VMSSiteCategory VMSSiteCategory { get; set; }
        public virtual VMSSiteCategory VMSSiteCategory1 { get; set; }
        public virtual VMSSpecificSite VMSSpecificSite { get; set; }
        public virtual Zone Zone { get; set; }
        public virtual VMSWaterShed VMSWaterShed { get; set; }
        public virtual VMSWeather VMSWeather { get; set; }
        public virtual VMSWindDirection VMSWindDirection { get; set; }
        public virtual ICollection<VMSSprayReportAgent> VMSSprayReportAgents { get; set; }
        public virtual ICollection<VMSSprayReportEmployee> VMSSprayReportEmployees { get; set; }
        public virtual ICollection<VMSSprayReportEquipment> VMSSprayReportEquipments { get; set; }
        public virtual ICollection<VMSSprayReportSurfactant> VMSSprayReportSurfactants { get; set; }
        public virtual ICollection<VMSUseLocation> VMSUseLocations { get; set; }
    }
}
