//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSSprayReportAgent
    {
        public string VMSSprayReportAgent_Key { get; set; }
        public string VMSSprayReport_Key { get; set; }
        public string VMSAgentProducts_Key { get; set; }
        public string VMSAgentSupplier_Key { get; set; }
        public string Activity_Key { get; set; }
        public double Quantity { get; set; }
        public string VMSAgentUOM_Key { get; set; }
        public string VMSAgentPurpose_Key { get; set; }
        public double Rate1 { get; set; }
        public string RateUOM1_Key { get; set; }
        public double Rate2 { get; set; }
        public string RateUOM2_Key { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual VMSAgentProduct VMSAgentProduct { get; set; }
        public virtual VMSAgentPurpose VMSAgentPurpose { get; set; }
        public virtual VMSAgentSupplier VMSAgentSupplier { get; set; }
        public virtual VMSAgentUOM VMSAgentUOM { get; set; }
        public virtual VMSSprayReport VMSSprayReport { get; set; }
    }
}
