//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSSprayReportEmployee
    {
        public string VMSSprayReportEmployee_Key { get; set; }
        public string VMSSprayReport_Key { get; set; }
        public string Employee_Key { get; set; }
        public double Hours { get; set; }
        public string Activity_Key { get; set; }
        public string Pay_Type_Key { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Pay_Type Pay_Type { get; set; }
        public virtual VMSSprayReport VMSSprayReport { get; set; }
    }
}
