//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSSiteCategory
    {
        public VMSSiteCategory()
        {
            this.VMSSpecificSites = new HashSet<VMSSpecificSite>();
            this.VMSSprayReports = new HashSet<VMSSprayReport>();
            this.VMSSprayReports1 = new HashSet<VMSSprayReport>();
        }
    
        public string VMSSiteCategory_Key { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<VMSSpecificSite> VMSSpecificSites { get; set; }
        public virtual ICollection<VMSSprayReport> VMSSprayReports { get; set; }
        public virtual ICollection<VMSSprayReport> VMSSprayReports1 { get; set; }
    }
}
