//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSSprayReportSurfactant
    {
        public string VMSSprayReportSurfactant_Key { get; set; }
        public string VMSSprayReport_Key { get; set; }
        public string VMSSurfactant_Key { get; set; }
        public decimal Quantity { get; set; }
        public string Activity_Key { get; set; }
        public string VMSAgentUOM_Key { get; set; }
        public double Rate1 { get; set; }
        public string RateUOM1_Key { get; set; }
        public double Rate2 { get; set; }
        public string RateUOM2_Key { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual VMSSprayReport VMSSprayReport { get; set; }
        public virtual VMSSurfactant VMSSurfactant { get; set; }
    }
}
