//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSTR
    {
        public string VMSTRS_Key { get; set; }
        public string Township { get; set; }
        public string Range { get; set; }
        public string SectionID { get; set; }
        public string County_Key { get; set; }
        public string CountyText { get; set; }
        public string TwnRngSec { get; set; }
    }
}
