//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSVegetationCode
    {
        public VMSVegetationCode()
        {
            this.VMSVegetations = new HashSet<VMSVegetation>();
        }
    
        public string VMSVegetationCode_Key { get; set; }
        public string VMSVegetationClass_Key { get; set; }
        public string USDACode { get; set; }
        public string CommonName { get; set; }
        public string ScientificName { get; set; }
        public Nullable<byte> Threatened { get; set; }
        public Nullable<byte> Endangered { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<VMSVegetation> VMSVegetations { get; set; }
        public virtual VMSVegetationClass VMSVegetationClass { get; set; }
    }
}
