//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSVegetation
    {
        public VMSVegetation()
        {
            this.VMSManagements = new HashSet<VMSManagement>();
            this.VMSUseLocations = new HashSet<VMSUseLocation>();
        }
    
        public string VMSVegetation_Key { get; set; }
        public string Name { get; set; }
        public string VMSVegetationClass_Key { get; set; }
        public string VMSVegetationCode_Key { get; set; }
        public string Road_Key { get; set; }
        public Nullable<decimal> BegMP { get; set; }
        public Nullable<decimal> EndMP { get; set; }
        public string VMSPlacement_Key { get; set; }
        public string Comments { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public byte Deleted { get; set; }
        public Nullable<int> AttachedDocuments { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<VMSManagement> VMSManagements { get; set; }
        public virtual VMSPlacement VMSPlacement { get; set; }
        public virtual ICollection<VMSUseLocation> VMSUseLocations { get; set; }
        public virtual VMSVegetationCode VMSVegetationCode { get; set; }
        public virtual VMSVegetationClass VMSVegetationClass { get; set; }
    }
}
