//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSWeather
    {
        public VMSWeather()
        {
            this.VMSSprayReports = new HashSet<VMSSprayReport>();
        }
    
        public string VMSWeather_Key { get; set; }
        public string Condition { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string SecurityUser_Key { get; set; }
    
        public virtual ICollection<VMSSprayReport> VMSSprayReports { get; set; }
    }
}
